### ISSUE TITLE
java.lang.UnsupportedOperationException: null

### ISSUE THREAD

**Issue by zzcoding** [liaochong/myexcel#108]
**Bug描述**
当html中有空的tr时 ，html转excel导出会报错
原因是HtmlTableParser.java的152行Collections.emptyList() 返回的时AbstractList  并未实现add方法，因此当调用到对象的add方法是或抛出java.lang.UnsupportedOperationException: null 异常
` if (tdElements.isEmpty()) {
            tr.setTdList(Collections.emptyList());
            tr.setColWidthMap(Collections.emptyMap());
            return;
        }`
修正：Collections.emptyList() 换成new LinkedList()

**Comment by liaochong** [comment]
感谢，明天修复发布
