### ISSUE TITLE
可不可以兼容下java8 以下啊，用1.7的编译过不了 有好多用的java8新特性

### ISSUE THREAD

**Issue by zzcoding** [liaochong/myexcel#109]
可不可以兼容下java8 以下啊，用1.7的编译过不了 有好多用的java8新特性

**Comment by liaochong** [comment]
这个不行，不仅仅是上层封装的java版本问题，主要是采用的poi特性所需版本需要java8，如果需要兼容需要做大量的改动，暂时不可行
