### ISSUE TITLE
超链接怎么加

### ISSUE THREAD

**Issue by adminpass** [liaochong/myexcel#111]
请问超链接怎么加
![image](https://user-images.githubusercontent.com/7523220/61757195-2a9af500-adf2-11e9-8eed-a1e2dcf57d26.png)
页面显示
![image](https://user-images.githubusercontent.com/7523220/61757213-3f778880-adf2-11e9-96fe-a21c2ae866b4.png)

**Comment by liaochong** [comment]
这是模板上加入超链接？

**Comment by adminpass** [comment]
@liaochong 是的，在Freemarker模板上加上链接，是否可以在
![image](https://user-images.githubusercontent.com/7523220/61758504-99c71800-adf7-11e9-97ff-ca2d8c9c7e25.png)
这里加个type，区分 Hyperlink？

**Comment by liaochong** [comment]
如果不是很急的话，可以稍微等两天，本周会支持超链接

**Comment by liaochong** [comment]
2.7.4版本支持链接，预计20190-07-28可用，具体使用方式：<td url="http://www.google.com" style="color:blue">链接内容</td>
