### ISSUE TITLE
title样式无法设置

### ISSUE THREAD

**Issue by geekeritcom** [liaochong/myexcel#121]
根据wiki文档的样例设置样式导出后标题样式没有改变，版本为最新版本
以下是我设置的字段上的样式示例代码
` @ExcelColumn(order = 2, title = "年龄", style = "title->font-weight:bold")
    private Integer age; `

**Comment by liaochong** [comment]
使用哪个类导出

**Comment by geekeritcom** [comment]
DefaultStreamExcelBuilder

**Comment by geekeritcom** [comment]
> 使用哪个类导出



> 使用哪个类导出

DefaultStreamExcelBuilder

**Comment by liaochong** [comment]
使用DefaultStreamExcelBuilder，需要调用hasStyle方法，默认不使用任何样式

**Comment by geekeritcom** [comment]
解决了，感谢您的回复，非常有帮助！
