### ISSUE TITLE
采用DefaultExcelBuilder+map方式构建一个大于10万的数据时，性能超慢

### ISSUE THREAD

**Issue by yaakua** [liaochong/myexcel#124]
对应的代码如下：
![image](https://user-images.githubusercontent.com/1543846/63632506-b1e5bd80-c669-11e9-8de4-89021be4f3da.png)

整个耗时如图：
![image](https://user-images.githubusercontent.com/1543846/63632493-882c9680-c669-11e9-9813-97a4621c6586.png)

是否有更加性能高的方式构建（要求还是使用map结构，因为需要动态拼装列和数据）

**Comment by liaochong** [comment]
DefaultExcelBuilder针对的是小批量数据，3.0.0版本正在重构，以期性能得到足够的提升，现在已经进入测试阶段

**Comment by liaochong** [comment]
为明确效果，能不能请你帮个忙，我这边提供一个jar包，您那边替换帮忙测试下效果？

**Comment by yaakua** [comment]
可以，请发我邮件，给我一个jar包，我测试一下 邮件 yaakua#126.com

**Comment by liaochong** [comment]
已发，请查收，版本2.8.4

**Comment by yaakua** [comment]
性能有所提升，相同数据下对比之前提升了50%。但是非常占用内存。默认设置的最大内存8G基本全被占用。

耗时情况：
-Build excel takes 371485 ms
内存占用情况：
![image](https://user-images.githubusercontent.com/1543846/63634060-e49caf80-c683-11e9-97fc-80ccd94bf438.png)

**Comment by yaakua** [comment]
另外采用： `FileExportUtil.export(workbook, file);`  方式生成文件也会非常耗时，并占用相当大的内存

**Comment by liaochong** [comment]
内存部分，有一部分代码没有提交，也做了相应调整，待会发给你

**Comment by liaochong** [comment]
2.8.5版本会提供map导出优化，但对于海量导出还需要等到3.0.0版本，提供相应的流式导出

**Comment by liaochong** [comment]
2.8.5版本已发布，请使用DefaultStreamExcelBuilder进行操作，具体请参阅文档
