### ISSUE TITLE
分别对标题和表格进行样式设置不生效

### ISSUE THREAD

**Issue by rboleynl** [liaochong/myexcel#128]
**Bug描述**
描述Bug产生的现象（A clear and concise description of what the bug is.）
分别对标题和表格进行样式设置不生效，只有title居中对齐，表格文字颜色未改变

**Bug复现**
按如下步骤复现（Steps to reproduce the behavior）:
@ExcelColumn(order = 5, title = "性别", index = 5, width = 10, style="title->text-align:center;cell->color:green")
private String gender;

**期望的结果**
期望的结果是什么（A clear and concise description of what you expected to happen.）
希望能对title和cell分别设置多个样式生效

**Comment by liaochong** [comment]
style="title->text-align:center;cell->color:green"修改为style={"title->text-align:center", "cell->color:green"}
