### ISSUE TITLE
注解中部分样式不生效

### ISSUE THREAD

**Issue by rboleynl** [liaochong/myexcel#129]
**Bug描述**
描述Bug产生的现象（A clear and concise description of what the bug is.）
部分样式不生效
**Bug复现**
按如下步骤复现（Steps to reproduce the behavior）:
代码:
@ExcelColumn(order = 0, title = "姓名", index = 0, style= {"title->font-weight:bold;", "cell->width:132px;"})
	private String userName;			//姓名

**期望的结果**
期望的结果是什么（A clear and concise description of what you expected to happen.）
字体加粗，宽度设置生效；尝试各种方式都不生效

**Comment by liaochong** [comment]
版本：2.8.5
测试代码：
Workbook workbook = DefaultExcelBuilder.of(ArtCrowd.class).autoWidthStrategy(AutoWidthStrategy.CUSTOM_WIDTH).fixedTitles().build(dataList);

@ExcelColumn(order = 3, index = 3, width = 20,style = {"title->font-weight:bold;","cell->color:green;width:100px"})
private String paintingLevel;

测试结果：
![image](https://user-images.githubusercontent.com/8674986/65656507-a7e12100-e052-11e9-9865-16d365b295bb.png)
正常

**Comment by rboleynl** [comment]
@liaochong 你把姓名、年龄都加上样式的话，姓名和年龄就不会生效了。

**Comment by rboleynl** [comment]
@liaochong 注解中title对应字段名，宽度、字体加粗才会生效，样式style中设置的width=100px不生效
![4FCDC30803B32E7E9DEEFDA08278CD0A](https://user-images.githubusercontent.com/10266095/65662602-40819c00-e067-11e9-88dd-d7df6d5de1d7.jpg)

**Comment by rboleynl** [comment]
不管是标题还是单元格文本如果为中文样式都失效

**Comment by liaochong** [comment]
抱歉，最近工作太忙，回复不及时，该问题已解决，国庆前发布

**Comment by rboleynl** [comment]
辛苦啦~
