### ISSUE TITLE
修改模板文档路径为绝对路径后报异常

### ISSUE THREAD

**Issue by liuwenchao124** [liaochong/myexcel#133]
**Bug描述**
当把例子里当模板文档路径改为绝对路径后，报找不到文件的异常

**Bug复现**
按如下步骤复现（Steps to reproduce the behavior）:
1. 修改例子里的代码的模板路径，我确定此文件存在：
@GetMapping("/freemarker/example")
    public void build(HttpServletResponse response) throws IOException {
        try (ExcelBuilder excelBuilder = new FreemarkerExcelBuilder()) {
            Map<String, Object> dataMap = this.getDataMap();
            Workbook workbook = excelBuilder.template("D:/20191005/freemarkerToExcelExample.ftl").build(dataMap);
//            Workbook workbook = excelBuilder.template("/templates/freemarkerToExcelExample.ftl").build(dataMap);
            AttachmentExportUtil.export(workbook, "freemarker_excel", response);
        }
    }
2.运行报错：
freemarker.template.TemplateNotFoundException: Template not found for name "D:/20191005/freemarkerToExcelExample.ftl".
The name was interpreted by this TemplateLoader: ClassTemplateLoader(classLoader="TomcatEmbeddedWebappClassLoader\r\n  context: ROOT\r\n  delegate: true\r\n----------> Parent Classloader:\r\nsun.misc.Launcher$AppClassLoader@14dad5dc\r\n", basePackagePath="").

**期望的结果**
正常运行

**Comment by liaochong** [comment]
目前模板构建只支持相对路径，即resources下获取文件，3.1.0.RELEASE版本会支持，如迫切需要，请先自行新建构建类，只需把下方设置为目录即可：
![image](https://user-images.githubusercontent.com/8674986/66270671-c502c480-e888-11e9-8657-1befb4858b38.png)
