### ISSUE TITLE
读取到科学计数法转成Double类型时报错

### ISSUE THREAD

**Issue by yaakua** [liaochong/myexcel#137]
**Bug描述**
描述Bug产生的现象（A clear and concise description of what the bug is.）
Excel当中有一个数字是0.0001 类似这样的小数，默认读取时会转成科学计数法（1E-3）
现有的转换类里面会先执行一句：
`PATTERN_NON_NUMBER.matcher(v).replaceAll("");`
这句话执行后就会将E字符去除了，导致后续执行` new BigDecimal(v)` 时报错。

![B6EF25B2-13B0-4FAD-9A94-9E5D41EF7EDF](https://user-images.githubusercontent.com/1543846/66470450-32e30200-eabc-11e9-955b-5db41dbe7081.png)

**Comment by yaakua** [comment]
![Uploading 2.png…]()

重新截图

**Comment by yaakua** [comment]
重新截图

**Comment by liaochong** [comment]
感谢，今晚修复，预计后天可用

**Comment by yaakua** [comment]
说明一下，我现在使用的版本是2.8.5

**Comment by liaochong** [comment]
3.0.0.RC1发布
