### ISSUE TITLE
关于导入方式的建议

### ISSUE THREAD

**Issue by pretty2010kit0** [liaochong/myexcel#147]
**导入方式建议**
目前导入方式必须使用注解，这在一些场景下是不方便的。可否考虑添加一个更灵活的导入方式，比如说可以指定titles，导出到List<Map>，这样使用场景可以更广。随便说一句，有些人是不太喜欢侵入式的注解形式的。

**Comment by pretty2010kit0** [comment]
导入到Map类型的List

**Comment by liaochong** [comment]
关于导入到Map类型的List，这个开发任务是有的，因为个人时间有限，按优先级开发还没来得及处理，按照目前的开发计划，3.1.0版本将会包含这个特性，感谢提议！！！
