### ISSUE TITLE
希望添加@ExcelColumn导入表、导出表自动映射的开关

### ISSUE THREAD

**Issue by wltj920** [liaochong/myexcel#150]
## 需求描述
目前`@ExcelColumn`的`mapping`属性可配置导出Excel时自动将某些类型（如数字、布尔）映射成字符串。但往往用户导出表格后，直接在表格上修改后进行导入，或者导入的数据使用字符而不是数据库中的数字或布尔。因此，希望添加新的功能，能够在`@ExcelColumn`注解上配置POJO类的导入导出是否开启映射。
## 功能建议
假设实现后的`User.java`注解如下：

```java
@ExcelColumn(index = 9, title = "用户状态", importMapping = "0:正常,1:密码锁定,2:管理员锁定", exportMapping="0:正常,1:密码锁定,2:管理员锁定")
private Integer userStatus;
```
* 在以上配置中，导入的Excel表`用户状态`列中的数据是`正常`，转换成的`userStatus`为**0**
* 在以上配置中，导出的Excel表`用户状态`列中的数据是`0`，转换成的`userStatus`为**正常**

**Comment by liaochong** [comment]
3.3.0.RELEASE发布
