### ISSUE TITLE
模板中单元格内容无法强制手工换行，设置单元格高度不生效

### ISSUE THREAD

**Issue by rboleynl** [liaochong/myexcel#156]
**Bug描述**
描述Bug产生的现象（A clear and concise description of what the bug is.）
模板文件中：
<th colspan="13" style="font-weight: bold;font-size: 14px;height: 160px;word-break: break-all;">填写须知：&lt;p&gt; ①  不可在本Excel表中添加、删除、修改表头，否则该模板失效；
使用word-break: break-all;样式内容会自动换行，但是不是期待的能强制换行；
使用标签&lt;p&gt; &lt;/p&gt; 、&lt;br/&gt; 、&lt;br>、\r\n、/r/n都没法强制换行；设置的height高度无效
**Bug复现**
按如下步骤复现（Steps to reproduce the behavior）:

**期望的结果**
期望的结果是什么（A clear and concise description of what you expected to happen.）
单元格能强制换行，能设置高度
![240DD451044006038173C76CD910FE6C](https://user-images.githubusercontent.com/10266095/67937929-71766300-fc09-11e9-933a-02689254e94a.jpg)

**Comment by liaochong** [comment]
3.0.3版本修复

**Comment by rboleynl** [comment]
换行生效了，但是单元格高度还是不生效；code:
<tr style="height: 160px;">

**Comment by rboleynl** [comment]
@liaochong

**Comment by liaochong** [comment]
在th上的tr确实存在无效现象，会跟随3.1.0发布，如果可以建议你先使用td代替th
