### ISSUE TITLE
td中含有特殊符号会被转义为html标记

### ISSUE THREAD

**Issue by rboleynl** [liaochong/myexcel#157]
**Bug描述**
描述Bug产生的现象（A clear and concise description of what the bug is.）
&lt;td&gt;中->类似字符串"爱新觉罗·玄烨" 中间有个点号会转化为&amp;middot;导出excel就不正常了。
**Bug复现**
按如下步骤复现（Steps to reproduce the behavior）:

**期望的结果**
期望的结果是什么（A clear and concise description of what you expected to happen.）
"爱新觉罗·玄烨" 中间有个点号不转化

**Comment by rboleynl** [comment]
jsoup解析html就给转义了

**Comment by liaochong** [comment]
3.1.0版本修复
