### ISSUE TITLE
Myexcel不能支持excel模板吗？

### ISSUE THREAD

**Issue by shimaomao** [liaochong/myexcel#160]
指定一个excel文件作为导出模板吗，是最迫切的导出需求，就是导出文件到一个现有的excel文件中，把数据灌进去，请问这个功能目前是不能支持的嘛？

**Comment by shimaomao** [comment]
感觉这个功能应该是支持的，我没找到对应的示例

**Comment by liaochong** [comment]
抱歉，以excel作为模板目前不支持，支持以html作为模板，如果是List< Bean >形式，DefaultStreamExcelBuilder也基本足够了，如果可能，能否描述下需求，看看myexcel是否满足

**Comment by shimaomao** [comment]
详细的需求是产品给定excel模板，其中excel模板中带有希望的格式，比如第一行表头上每个列名，以及每列的详细备注，可以使用excel的标注功能给出，我们获取list<bean>数据之后，按照产品预先设置的表头及格式，讲数据导出到模板中。

**Comment by shimaomao** [comment]
![image](https://user-images.githubusercontent.com/17241143/68816176-96161480-06b8-11ea-865b-865d3d9198b1.png)

**Comment by shimaomao** [comment]
![image](https://user-images.githubusercontent.com/17241143/68816240-c9f13a00-06b8-11ea-8b3c-0087d3a829d6.png)

**Comment by liaochong** [comment]
按你的需求，除了注释外其他DefaultExcelBuilder都是支持的

**Comment by shimaomao** [comment]
上面的表头格式都自己代码写出来吗？不能直接套用一个现成的excel的表格头吧？有计划支持这样的需求吗？

**Comment by liaochong** [comment]
MyExcel基本完全屏蔽了直接的POI操作，DefaultExcelBuilder可以通过css样式以及注解属性定制格式，比如背景色，字体等等都是可以的，另外上面描述的必填项，可以通过下拉框来限制，这些DefaultExcelBuilder都可以直接做到的
