### ISSUE TITLE
DefaultStreamExcelBuilder append列数据之后，可以从获取的DefaultStreamExcelBuilder中重新读取出列数据么

### ISSUE THREAD

**Issue by yunfeiyao** [liaochong/myexcel#162]
现在有一个业务现象是，DefaultStreamExcelBuilder append列数据之后，
我需要从方法中获取的DefaultStreamExcelBuilder对象中重新读取出列数据，
请问能不能实现

**Comment by liaochong** [comment]
你的意思是append后立马读取已经append的excel数据？

**Comment by yunfeiyao** [comment]
append后，由于目前的项目不能大规模改动，业务逻辑是 需要获取表格数据，但是可以目前在已有方法中，只可以获取到DefaultStreamExcelBuilder append完数据的对象，如果再次生成Excel，读取Excel后其实也可以获取数据。但是我希望可以直接从获取到的DefaultStreamExcelBuilder 中直接读取append进去的数据。在阅读源码中发现是放在了流工厂HtmlToExcelStreamFactory 的trWaitQueue队列中，不知道是不是可以直接从队列中读出所有append的数据

**Comment by liaochong** [comment]
不是很明白，如果你想获取被append的数据，可以在append之前自行保留一份数据，为什么要从trWaitQueue获取呢？

**Comment by yunfeiyao** [comment]
因为目前改变不了它的已有方法，我是从另一个方法A去调用它这个方法B，B方法返回的只有DefaultStreamExcelBuilder对象，append之前即使自行保留一份数据，我这边也是获取不了的。而且不能修改已有方法的返回类型，所以现在就只能从DefaultStreamExcelBuilder着手思考如何获取列数据了

**Comment by liaochong** [comment]
这种情况表示无能为力了，因为即使开放出trWaitQueue，它也是不断被消费的，无法提供准确的数据，而且这种需求也不太适合出现在MyExcel，请见谅！！！
