### ISSUE TITLE
还需要额外引入poi依赖吗？

### ISSUE THREAD

**Issue by qinkangdeid** [liaochong/myexcel#174]
**Bug描述**
描述Bug产生的现象（A clear and concise description of what the bug is.）
- 版本
  > 3.3.0-GA
- 导出的时候提示找不到部分依赖
![image](https://user-images.githubusercontent.com/17582522/71457307-38f1a080-27d8-11ea-975d-1a468c3ffc3e.png)

查看myexcel的依赖是引用了：
![image](https://user-images.githubusercontent.com/17582522/71457338-6dfdf300-27d8-11ea-8deb-965d12b4fbf9.png)

**Comment by liaochong** [comment]
不需要，你需要做的是排除依赖，myexcel依赖的poi版本为4.1.1

**Comment by qinkangdeid** [comment]
了解了  多谢大佬 🙏
