### ISSUE TITLE
版本3.2.2 导入excel，只能根据index指定列，使用title不生效

### ISSUE THREAD

**Issue by penghs520** [liaochong/myexcel#179]
版本3.2.2 导入excel，只能根据index指定列，使用title不生效

**Comment by liaochong** [comment]
请给下bean定义

**Comment by penghs520** [comment]
👌。我放在附件中，目前我在字段上添加的注解是这样的&nbsp;@ExcelColumn(order = 0, title = "姓名",index = 0)。之前@ExcelColumn(title = "姓名")不成功。顺便提一下，时间格式的一段报错 


表格数据如下：

字段注解如下：



注：以上测试基于版本3.3.1&nbsp; &nbsp; 。具体bean在附件中。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"清沐"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月8日(星期三) 晚上6:01
收件人:&nbsp;"liaochong/myexcel"<myexcel@noreply.github.com&gt;;
抄送:&nbsp;"彭洪思"<1546795587@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liaochong/myexcel] 版本3.2.2 导入excel，只能根据index指定列，使用title不生效 (#179)




请给下bean定义

**Comment by liaochong** [comment]
不好意思，没看到附件，几点：
1.请升级到最新版本-3.3.1，尝试问题有没有解决；
2.用title读取时，bean中所有@ExcelColumn列不允许有index，只要有一个index，都会按index读取

**Comment by liaochong** [comment]
本地使用3.3.1版本正常，无法重现，请问你那边是否正常，如果正常的话那我关闭该问题了

**Comment by penghs520** [comment]
以下是我的测试demo 附件


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"清沐"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月10日(星期五) 中午11:47
收件人:&nbsp;"liaochong/myexcel"<myexcel@noreply.github.com&gt;;
抄送:&nbsp;"彭洪思"<1546795587@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liaochong/myexcel] 版本3.2.2 导入excel，只能根据index指定列，使用title不生效 (#179)




本地使用3.3.1版本正常，无法重现，请问你那边是否正常，如果正常的话那我关闭该问题了

**Comment by penghs520** [comment]
暂时测试未通过，我下午再尝试一下。或者您可以将你测试通过的demo 以及excel给我发一份吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "清沐"<notifications@github.com&gt;; 
发送时间: 2020年1月10日(星期五) 中午11:47
收件人: "liaochong/myexcel"<myexcel@noreply.github.com&gt;; 
抄送: "彭洪思"<1546795587@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [liaochong/myexcel] 版本3.2.2 导入excel，只能根据index指定列，使用title不生效 (#179)




本地使用3.3.1版本正常，无法重现，请问你那边是否正常，如果正常的话那我关闭该问题了

**Comment by liaochong** [comment]
你读取excel的类是什么？是SaxExcelReader吗，目前仅它支持，另外，还需要满足所有@ExcelColumn中不允许有index属性

**Comment by penghs520** [comment]
可以了，我之前用DefaultExcelReader。现在改为SaxExcelReader。感谢感谢，你真棒！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "清沐"<notifications@github.com&gt;; 
发送时间: 2020年1月10日(星期五) 中午1:27
收件人: "liaochong/myexcel"<myexcel@noreply.github.com&gt;; 
抄送: "彭洪思"<1546795587@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [liaochong/myexcel] 版本3.2.2 导入excel，只能根据index指定列，使用title不生效 (#179)




你读取excel的类是什么？是SaxExcelReader吗，目前仅它支持，另外，还需要满足所有@ExcelColumn中不允许有index属性

**Comment by liaochong** [comment]
因文档还不够细致给你们带来不便表示抱歉，后续不断完善，感谢支持！！！
