### ISSUE TITLE
数据按照默认模式导出excel，再以SAX方式进行导入，提示excel版本最低2007

### ISSUE THREAD

**Issue by penghs520** [liaochong/myexcel#182]
**Bug描述**
描述Bug产生的现象（A clear and concise description of what the bug is.）

**Bug复现**
按如下步骤复现（Steps to reproduce the behavior）:

**期望的结果**
期望的结果是什么（A clear and concise description of what you expected to happen.）

**Comment by liaochong** [comment]
请提供下全部异常，如果可以的话，希望能够提供对应的excel，方便复现，谢谢
