### ISSUE TITLE
想要默认计算宽度，但是不希望有斑马纹背景

### ISSUE THREAD

**Issue by yunfeiyao** [liaochong/myexcel#183]
默认导出默认计算宽度、斑马线背景色，使用noStyle()方法去除的是所有的样式，请问默认计算宽度怎么增加呢

**Comment by liaochong** [comment]
DefaultExcelBuilder.of(xx.class).widthStrategy(WidthStrategy.COMPUTE_AUTO_WIDTH).build

**Comment by liaochong** [comment]
noStyle默认只是去除样式，宽度策略是不变的，你使用的是哪个版本？如果使用noStyle后宽度策略变了，请先升级为3.3.1，如还是不行，请贴下对应的代码以及excel截图，谢谢

**Comment by liaochong** [comment]
请问问题解决了吗？如果解决了，就关闭该问题了

**Comment by yunfeiyao** [comment]
你好，暂时没有。我周一再试一下




| |
姚云飞
|
|
邮箱：yaoyunfei1996@163.com
|

签名由 网易邮箱大师 定制

在2020年01月11日 22:36，清沐 写道：

请问问题解决了吗？如果解决了，就关闭该问题了
