### ISSUE TITLE
DefaultExcelReader导出时单元格样式统一设为String

### ISSUE THREAD

**Issue by sjtuff** [liaochong/myexcel#185]
现在DefaultExcelReader导出时会把很长的数字转为科学计数法，但是不希望这样，希望以原来的数字导出，怎么设置

**Comment by liaochong** [comment]
@ExcelColumn(convertToString=true)强制转换为字符串，或者使用format格式化

**Comment by sjtuff** [comment]
每一列的宽度太窄了，显示不全，自动计算好像没成功，没有使用@Column注解，使用的titles和fieldDisplayOrder设每一列的，如何指定宽度

**Comment by liaochong** [comment]
如果使用动态导出，可使用widths(20,30,40)指定宽度，单位为字符，可使用.widthStrategy(WidthStrategy.COMPUTE_AUTO_WIDTH)使用自动计算

**Comment by sjtuff** [comment]
widths要从第一列开始指定长度，有只指定某一列的方法吗

**Comment by sjtuff** [comment]
DefaultStreamExcelBuilder的widths(10,20,30,40)没有起作用，autoWidthStrategy(AutoWidthStrategy.COMPUTE_AUTO_WIDTH)也没有起作用，宽度还是一样的

**Comment by liaochong** [comment]
代码贴一下

**Comment by liaochong** [comment]
本地3.3.1版本，代码如下：
DefaultStreamExcelBuilder<ArtCrowd> defaultExcelBuilder = DefaultStreamExcelBuilder.of(ArtCrowd.class)
                .widthStrategy(WidthStrategy.COMPUTE_AUTO_WIDTH)
                .threadPool(Executors.newFixedThreadPool(10))
                .start()
![image](https://user-images.githubusercontent.com/8674986/72311637-4ce63f00-36c0-11ea-92ef-bf209af35eba.png)
正常

**Comment by sjtuff** [comment]
DefaultStreamExcelBuilder streamExcelBuilder = DefaultStreamExcelBuilder.getInstance(); 
streamExcelBuilder.sheetName("sheet1").titles(titles).fieldDisplayOrder(orders).start();
 streamExcelBuilder.autoWidthStrategy(AutoWidthStrategy.COMPUTE_AUTO_WIDTH);
 try {
            Workbook workbook = streamExcelBuilder.build();
             excelFileName = "." + File.separator + fileName + ".xlsx";
            file = new File(excelFileName);
            FileExportUtil.export(workbook, file);
        } catch (IOException e) {
            log.error(e.getMessage(), e);
        }

**Comment by sjtuff** [comment]
widthStrategy没找到这个方法，只有autoWidthStrategy

**Comment by liaochong** [comment]
版本升级为3.3.2吧

**Comment by sjtuff** [comment]
好的，谢谢

**Comment by liaochong** [comment]
是否正常？如正常，请关闭该问题哈
