### ISSUE TITLE
带公式的Excel导入使用sax解析如何处理？

### ISSUE THREAD

**Issue by CalmArrow** [liaochong/myexcel#190]
**Bug描述**
- 表格列数较多，部分列数据是由前几列通过公式计算出来的，在使用Sax解析时无法正确解析，只能读取到23条，且数据错乱
- 但如果把表格导成csv格式，就可以正常读取了

**期望的结果**
期望能够正确读取公式计算的值

**Comment by liaochong** [comment]
能否提供下对应的excel？

**Comment by liaochong** [comment]
无后续反馈，该问题关闭
