### ISSUE TITLE
能否提供excel模板插值的方式导出

### ISSUE THREAD

**Issue by sky1983** [liaochong/myexcel#193]
首先感谢辛苦提供的开源软件，给日常工作带来了很大的方便，也大大减少了开发的时间
不知道能否提供类似于http://easypoi.mydoc.io/#text_225967这样的实现方式。
另外还有一个问题是，如果需要隐藏导出文件中的某一列，通过设置宽度为0好像是不可以的，不知道是否有这个功能
谢谢！

**Comment by liaochong** [comment]
这个功能正在规划中，感谢使用！

**Comment by liaochong** [comment]
目前版本没有，隐藏某一列这个功能会在3.4.0.RC4提供，预计是20号前后

**Comment by sky1983** [comment]
目前在@ExcelColumn设置width=0是不能隐藏列的，查看代码发现width必须大于0才会被使用，通过设置widths确实可以实现功能，但是如果跨列设置的话，就必须给中间的每个列都设置宽带，操作起来不是很方便，目前采用设置style = {"title->width:0px",
    "cell->width:0px"}的方式实现了功能，如果能提供一个独立的设置，或者直接设置width=0能实现就会方便很多。

**Comment by liaochong** [comment]
是的，已提供，正在测试中
![image](https://user-images.githubusercontent.com/8674986/74587694-f65a8080-5030-11ea-824b-3b1d003055a7.png)

**Comment by sky1983** [comment]
辛苦了，非常感谢！

**Comment by liaochong** [comment]
3.4.0.RELEASE已发布，注解width、hideColumns方法、width方法均支持隐藏列，如有其他任何问题，可随时联系

**Comment by sky1983** [comment]
已经更新，非常感谢
