### ISSUE TITLE
English documentation

### ISSUE THREAD

**Issue by kortov** [liaochong/myexcel#194]
Hello, I see that you've done a great job writing this library, but for non-chinese speakers it's hard and risky to use. Do you have plans to translate at least wiki\readme?

**Comment by liaochong** [comment]
Thanks for using the library. The early stage is mainly to improve the functions, so there is not much investment in internationalization. At present, the basic functions of the library have been stable, and documents will become the focus of attention. In the near future, readme and Wiki in Chinese and English will be provided. We look forward to your joining us to improve the library and documents.

**Comment by kortov** [comment]
I haven't seen these english articles. Did you add them yesterday? It's really cool! :) 
![image](https://user-images.githubusercontent.com/6348215/74716494-1c0da280-5248-11ea-9230-93800e268f53.png)

**Comment by liaochong** [comment]
Yes, but due to the hurry, there may be some errors in the document, which will be improved in the future
