### ISSUE TITLE
wiki文档的下拉列表没有详细说明，用出来不对

### ISSUE THREAD

**Issue by xinhaiCai** [liaochong/myexcel#202]
**Bug描述**
参照文档用法：
@ExcelColumn(title="下拉列表")
    List<String> options = Arrays.asList("1","2","3");
效果如下：
上传不了图片

**期望的结果**
正常的下拉列表用法

**Comment by liaochong** [comment]
请提供下版本以及代码

**Comment by liaochong** [comment]
3.4.1版本测试无问题，请尝试使用3.4.1版本，如还有问题，庆截图后直接粘贴到内容框即可上传
![image](https://user-images.githubusercontent.com/8674986/75137009-5f24b580-5721-11ea-9372-37be7e70f477.png)

**Comment by liaochong** [comment]
无后续反馈，该问题默认已解决

**Comment by xinhaiCai** [comment]
版本是2.8.2

**Comment by xinhaiCai** [comment]
而且用法没给出，默认选择项或者说生日哪一年，动态赋值的情况下还能用下拉选框修改

**Comment by liaochong** [comment]
升级到最新版后是否正常？预选这个功能这边参考下官方文档，尽快提供

**Comment by xinhaiCai** [comment]
这边不方便升级，是由内部平台集成不同依赖和内部框架的版本~

**Comment by liaochong** [comment]
也就是myexcel是你们内部开发的版本？

**Comment by xinhaiCai** [comment]
不是，只是集成到我们平台框架作为内部开发平台而已

**Comment by liaochong** [comment]
那没关系，你可以在你的项目中引用，覆盖平台框架的版本即可，不影响其他项目，而且当前只是测试，如果确实有问题，平台框架也需要升级版本

**Comment by liaochong** [comment]
另外，也强烈建议升级，高版本对于导入导出的性能做了很多的优化，比如读取百万数据内存占用也占用很低等等

**Comment by xinhaiCai** [comment]
那高版本同时支持默认选项和预选项列表吗？

**Comment by liaochong** [comment]
下拉列表，默认第一个就是被选择项

**Comment by xinhaiCai** [comment]
额，这样就不能支持导出的数据各异，同时又允许修改了
