### ISSUE TITLE
导出图片报错

### ISSUE THREAD

**Issue by JimmyiZhang** [liaochong/myexcel#204]
**Bug描述**
导出图片异常，具体如下：
1. 导出bmp图片，异常
java.lang.RuntimeException: java.lang.IllegalThreadStateException: An exception occurred while processing at com.github.liaochong.myexcel.core.DefaultExcelBuilder.build(DefaultExcelBuilder.java:164)
2. 导出jpg大图片（大于2M），没有异常信息，导出excel没有该图片

**Bug复现**
// 实体类
@ExcelModel(rowHeight = 1000, sheetName = "参考图片")
public class OrderOrderReferenceExcel {
    @ExcelColumn(title = "名称", width = 20, style = "cell->word-break: break-all;")
    private String name;

    @ExcelColumn(title = "图片", width = 20, fileType = FileType.IMAGE)
    private File file;
}

// 实现方法
List<OrderOrderReferenceExcel> sheet5 = exportOrderReference(refFiles);
Workbook workbook5 = DefaultExcelBuilder.of(OrderOrderReferenceExcel.class, workbook4)
                    .build(sheet5);
AttachmentExportUtil.export(workbook5, "任务明细表信息", response);

**期望的结果**
导出成功

**Comment by liaochong** [comment]
请说明下版本，谢谢

**Comment by JimmyiZhang** [comment]
版本3.4.1

**Comment by liaochong** [comment]
感谢，尽快解决该问题

**Comment by liaochong** [comment]
问题一：按poi官方文档，当前仅支持以下类型图片，后续版本将会添加相应错误提示
![image](https://user-images.githubusercontent.com/8674986/75556226-c079bb00-5a78-11ea-97b4-4348f27933ee.png)

**Comment by liaochong** [comment]
问题二：3.4.1版本导出16M jpg图片正常导出，建议排查下导出的File是否真实存在图片

**Comment by JimmyiZhang** [comment]
感谢回复
1. 经过测试，同样是jpg文件发现有的图片可以显示，有的图片不能显示
2. 没显示的图片，长宽属性均为0，设置相应的长宽可以正常显示

**Comment by JimmyiZhang** [comment]
@liaochong 导出excel中图片的长宽为0是什么原因？该如何处理？

**Comment by liaochong** [comment]
能否提供下对应的图片以及生成的excel？

**Comment by JimmyiZhang** [comment]
请查收附件
[export.zip](https://github.com/liaochong/myexcel/files/4271294/export.zip)

**Comment by liaochong** [comment]
图片宽度为0的问题，已找到问题，今晚修复，预计明天可用-版本3.4.2

**Comment by JimmyiZhang** [comment]
辛苦了，再次感谢
期待新版本

**Comment by liaochong** [comment]
如果可以，希望能够帮忙测试下，保证新版本真实可用

**Comment by JimmyiZhang** [comment]
没问题

**Comment by liaochong** [comment]
已发送jar至邮箱，请查收

**Comment by JimmyiZhang** [comment]
测试了多个jpg和png，目前测试一切正常
后期项目会继续测试，有问题我再反馈

另外，现在的图片是按照单元格平铺的，可以考虑增加单元格内自适应选项

**Comment by liaochong** [comment]
3.4.2已发布，明天可用，另外，当前图片是自适应单元格的

**Comment by JimmyiZhang** [comment]
感谢
现在应该是单元格填充吧
我的意思是单元格内图片长宽比锁定，保持原始比例，不至于图片变形

**Comment by liaochong** [comment]
ok，明白了，后续改进，如您在使用过程中先行改进，欢迎提交代码

**Comment by JimmyiZhang** [comment]
对poi不太熟悉，可以尝试一下
