### ISSUE TITLE
使用AttachmentExportUtil导出原始文件被删除

### ISSUE THREAD

**Issue by sky1983** [liaochong/myexcel#205]
**Bug描述**
使用com.github.liaochong.myexcel.utils.AttachmentExportUtil中的export(Path path, String fileName, HttpServletResponse response) 方法，原始文件被删除

**期望的结果**
希望增加一个参数，是否删除历史文件，因为有些时候是需要保留历史文件的

谢谢

**Comment by liaochong** [comment]
导出删除的是临时文件，命名等具有非可读性，且存储在项目根路径下，如需保留文件建议使用FileExportUtil导出到指定目录

**Comment by sky1983** [comment]
在我的应用场景中，系统会提前准备好压缩文件包，需要借助AttachmentExportUtil的导出方法将文件输出到客户端，而原文件需要做保留，不知道这个场景是否通用，而我查看了FileExportUtil并无类似方法

**Comment by liaochong** [comment]
能够理解你的应用场景，但AttachmentExportUtil是完全为了MyExcel服务的，对于AttachmentExportUtil的拓展修改也需要基于MyExcel，你的提议对于MyExcel暂时没有使用场景，不添加对MyExcel无用的功能，以保持MyExcel的纯净与简洁，因此建议新建工具类来实现对应功能，望请见谅！

**Comment by sky1983** [comment]
好的，了解
