### ISSUE TITLE
rename the project

### ISSUE THREAD

**Issue by MkkOF** [liaochong/myexcel#207]
把项目名称和maven的名称改个名字吧，myexcel这种太low了吧，好东西别因为名字被忽略了

**Comment by liaochong** [comment]
非常感谢您的认可以及提议，一来是本人确实想不出什么特别好的名字，另外也是因为目前myexcel使用用户也有不少，如果改名字，会对历史用户升级造成麻烦，所以短期内不会变更项目名称
