### ISSUE TITLE
Css border style name and values mismathch

### ISSUE THREAD

**Issue by kortov** [liaochong/myexcel#208]
**Bug描述**
In styles class https://github.com/liaochong/myexcel/blob/edbd17e53b2194b673f09e9f9e4cf9baec1ffe2b/src/main/java/com/github/liaochong/myexcel/core/style/BorderStyle.java#L30-L38
are defined props border-* -style which accept `thin` value, but border-* -style doesn't have `thin` value https://www.w3schools.com/cssref/pr_border-style.asp

but  [border](https://www.w3schools.com/cssref/pr_border.asp)  and [border-width](https://www.w3schools.com/cssref/pr_border-width.asp)  do 

Intellij IDEA marks a warning here 
![image](https://user-images.githubusercontent.com/6348215/75797995-625a1a00-5d8f-11ea-8e07-c53b8036f10f.png)

**期望的结果**
期望的结果是什么（A clear and concise description of what you expected to happen.）
border-* -style should be replaced or extended with border or border-width

**Comment by liaochong** [comment]
Thank you very much. There is something wrong with the border style. It will be corrected as soon as possible

**Comment by liaochong** [comment]
As for the problem of missing value matching, because the POI and CSS styles are slightly different, I need to think about how to make them compatible to the greatest extent. Therefore, 3.5.0 still does not support the border width style
