### ISSUE TITLE
Feature request Add style for just border (replacing all four variants)

### ISSUE THREAD

**Issue by kortov** [liaochong/myexcel#209]
In css if you just set `style = "border:thin"` all 4 borders will be thin, add this behaviour please.

Now it doesn't work https://github.com/liaochong/myexcel/blob/edbd17e53b2194b673f09e9f9e4cf9baec1ffe2b/src/main/java/com/github/liaochong/myexcel/core/style/BorderStyle.java#L47-L67

related to #208

**Comment by liaochong** [comment]
In version 3.5.0, a new border style is added to set the styles of four borders at the same time, such as: border style: solid thin

**Comment by kortov** [comment]
thank you for solving all my last issues
