### ISSUE TITLE
Wiki improve template link example

### ISSUE THREAD

**Issue by kortov** [liaochong/myexcel#210]
**Bug描述**
In example https://github.com/liaochong/myexcel/wiki/Excel-template-build#3template-example is not obvious how to provide url for link `<td url>百度地址</td>`

**期望的结果**
期望的结果是什么（A clear and concise description of what you expected to happen.）
change a line to something like `<td url="http://localhost/">百度地址</td>`

**Note
BTW all custom styles override link styles at the moment of current master edbd17e53b2194b673f09e9f9e4cf9baec1ffe2b so I for an hour thought that I do something wrong with links and they doesn't work :laughing:  (but they just didn't have a link style). Maybe you have some thoughts on this?

**Comment by liaochong** [comment]
At present, such settings can meet your needs, and subsequent hyperlinks will have default styles.
`<td  colspan="3" style="color:blue;text-decoration: underline"><a href="http://www.baidu.com">百度链接</a> </td>`

**Comment by liaochong** [comment]
Version 3.5.0 has been released. Links have blue and underline styles
