### ISSUE TITLE
wiki improvement height example

### ISSUE THREAD

**Issue by kortov** [liaochong/myexcel#214]
I guess height style only applied to `<tr>` so maybe you should write about it in the [wiki](https://github.com/liaochong/myexcel/wiki/Style-support#height) 
And I think example should be with pt not px, as it written in the code
https://github.com/liaochong/myexcel/blob/362bfccd072a12eefc50f2a84b803d7e567d07c0/src/main/java/com/github/liaochong/myexcel/core/AbstractExcelFactory.java#L206-L208

like `<tr style="height: 45pt">`

Yeah I see , that `pt` and `px` doesn't matter, you only take `int` part, but with `pt` it's more concise https://github.com/liaochong/myexcel/blob/362bfccd072a12eefc50f2a84b803d7e567d07c0/src/main/java/com/github/liaochong/myexcel/utils/TdUtil.java#L91-L98

**Comment by liaochong** [comment]
The document for setting the template row height has been added to the wiki. As for the unit, it will be refined in the following continuous improvement of style support.

https://github.com/liaochong/myexcel/wiki/Template-row-height-setting
