### ISSUE TITLE
Feature request "width: auto"

### ISSUE THREAD

**Issue by kortov** [liaochong/myexcel#220]
As I understand, you can either set all widths manually or set it automatically with `.widthStrategy(WidthStrategy.COMPUTE_AUTO_WIDTH)` but you can't do both. I guess style `width: auto` could solve this problem and I think it's technically is possible, you only need to rearrange and improve lines from `HtmlTableParser`?

https://github.com/liaochong/myexcel/blob/2fccb06243ad92de102372272017df934de26d60/src/main/java/com/github/liaochong/myexcel/core/parser/HtmlTableParser.java#L243-L250

**Comment by liaochong** [comment]
I don't quite understand what you mean. At present, `COMPUTE_AUTO_WIDTH` and the width of active settings can coexist in part. The width of active settings will cover `COMPUTE_AUTO_WIDTH`

**Comment by kortov** [comment]
I didn't know about that, I'll test it

**Comment by kortov** [comment]
@liaochong I pushed a test example to the branch https://github.com/kortov/myexcel/tree/test-width-example-220

you can see that I set widths manually 

```
<tr>
            <th style="width: 1pt">Category</th>
            <th style="width: 1pt">Product Name</th>
            <th style="width: 1pt">Count</th>
    </tr>
```

but it produces excel with auto width 
![image](https://user-images.githubusercontent.com/6348215/77334687-972e1100-6d3e-11ea-9944-9448544597d8.png)

**Comment by kortov** [comment]
I expect on COMPUTE_AUTO_WIDTH autocomputing of cells where I didn't set width manually and my custom width where I set it. In variants NO_AUTO, AUTO_WIDTH, COMPUTE_AUTO_WIDTH and @Deprecate CUSTOM_WIDTH I don't know what to choose. 

And I see no wiki about it, is it there? :)

And honestly, I don't understand difference between AUTO_WIDTH and COMPUTE_AUTO_WIDTH

**Comment by liaochong** [comment]
Version 3.5 has implemented the ability to customize the width coverage strategy. I will test your example to see if there is a bug. In addition, AUTO_WIDTH is consistent with the adaptive width in Excel, while COMPUTE_AUTO_WIDTH is estimated by the code according to the cell content, with poor accuracy

**Comment by kortov** [comment]
> In addition, AUTO_WIDTH is consistent with the adaptive width in Excel, while COMPUTE_AUTO_WIDTH is estimated by the code according to the cell content

Ah, I see, I didn't understand that

I edited my previous comment, I hope it's not confusing :) And sorry for bothering you
