### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.poi.xssf.usermodel.XSSFColor.<init>(Ljava/awt/Color;Lorg/apache/poi/xssf/usermodel/IndexedColorMap;)V

### ISSUE THREAD

**Issue by cielswift** [liaochong/myexcel#221]
java.lang.NoSuchMethodError: org.apache.poi.xssf.usermodel.XSSFColor.<init>(Ljava/awt/Color;Lorg/apache/poi/xssf/usermodel/IndexedColorMap;)V

具体的版本对应是什么?

**Comment by liaochong** [comment]
这是包冲突导致的，poi 版本需要4.0版本以上，建议4.1.1版本

**Comment by cielswift** [comment]
谢谢 , 请问导入导出的时候如何 映射呢? 只能用mapping  简单映射，如"1:男,2:女" 吗? 怎么自定义映射呢?

**Comment by cielswift** [comment]
不好意思 ,还有一个问题是怎么设置为文本格式呢?  @ExcelColumn(... convertToString=true ) 无效;

**Comment by liaochong** [comment]
目前映射只能用简单映射，如不满足请自行代码转换，后续会补充该功能

**Comment by liaochong** [comment]
转换文本这种应该是可以的，有图吗

**Comment by cielswift** [comment]
导出正常,但是在excel中编辑太长的数字就变成科学计数法了; 必须手动设置为文本格式;

**Comment by liaochong** [comment]
这是excel本身的操作，导出程序无能为力

**Comment by cielswift** [comment]
谢谢,这对我意义重大
