### ISSUE TITLE
无法获取真实rownum

### ISSUE THREAD

**Issue by frank1197** [liaochong/myexcel#222]
当excel中，存在空行的情况下，myexcel的read()中，会忽略空行。
但如果在后面的excel中数据出错的情况下，无法获取真实的行号来给用户提醒。

**期望的结果**
能够获取到真实数据行号

**Comment by liaochong** [comment]
会尽快修复该问题，感谢🙏

**Comment by liaochong** [comment]
能否提供文件或者截图（文件类型）以及读取代码以便测试？

**Comment by crgoodjob** [comment]
![image](https://user-images.githubusercontent.com/31612301/105346654-deb45080-5c20-11eb-8caa-a9a8a03c0281.png)
excel6行数据中间有一行空行，读取数据会忽略空行。然后回写批注时会行对应错误。
excel读取：
private List<Pf2ndUpCommCollectInfoVo> pf2ndExcelReadPf2ndUpCommCollectInfoVo(File excel, int index) {
        List<Pf2ndUpCommCollectInfoVo> list = SaxExcelReader.of(Pf2ndUpCommCollectInfoVo.class)
                .sheet(index)
                .rowFilter(row -> row.getRowNum() > 0)
                .read(excel);
        return list;
    }

**期望结果**：
读取excel时能包括真实行号，或者不忽略空行

**Comment by crgoodjob** [comment]
这种方式取得了行号，虽然没有读取到空行，但是貌似行号没错
readThen(excel, (obj, context) -> {
    obj.setId(String.valueOf(context.getRowNum()));
    list.add(obj);
});

**Comment by liaochong** [comment]
read(excel,(value, context)->{context.getRowNum()})
