### ISSUE TITLE
建议将默认的FreemarkerExcelBuilder中的freemarker Configuration暴露出来

### ISSUE THREAD

**Issue by twj373493437** [liaochong/myexcel#224]
建议将默认的FreemarkerExcelBuilder中的freemarker Configuration加个静态get方法暴露出来，以便于修改配置。我现在的解决办法是copy了一遍FreemarkerExcelBuilder然后改的。

**Comment by liaochong** [comment]
请问什么场景下需要修改？

**Comment by twj373493437** [comment]
> 请问什么场景下需要修改？

我遇到的情况是freemarker对Java8的时间类型如LocalDateTime支持不太好，然后我配置了一个ObjectWrapper。

**Comment by liaochong** [comment]
关于配置透出我想下方案，你那边能否将你对LocalDateTime的支持代码提交到github，以帮助其他用户呢？

**Comment by kortov** [comment]
Sorry, I don't know Chinese lang, but as I understand, you can't provide config for Freemarker? I stumbled upon this issue with Freemarker when templated e-mails and used https://github.com/lazee/freemarker-java-8 (I guess you too). So I guess this issue has a point

**Comment by twj373493437** [comment]
> 关于配置透出我想下方案，你那边能否将你对LocalDateTime的支持代码提交到github，以帮助其他用户呢？

我是参考这篇博客配置的 https://blog.csdn.net/feleon/article/details/99588121

**Comment by twj373493437** [comment]
> Sorry, I don't know Chinese lang, but as I understand, you can't provide config for Freemarker? I stumbled upon this issue with Freemarker when templated e-mails and used https://github.com/lazee/freemarker-java-8 (I guess you too). So I guess this issue has a point

Thank you, it`s very useful to me.

**Comment by liaochong** [comment]
3.7.0版本补充了freemarker对java8的日期支持，对于配置透出，后续版本优化
