### ISSUE TITLE
html2excle问题

### ISSUE THREAD

**Issue by sailsoft2088** [liaochong/myexcel#231]
发现把表格导出为excel时只支持每个table单独导出为sheet，在修改为导出多table为一个sheet时发现单元格合并取值有问题，建议修改为如下方式：
            sheet.addMergedRegion(new CellRangeAddress(currentRow.getRowNum(), td.getRowSpan() > 0 ? currentRow.getRowNum() + td.getRowSpan() - 1 : currentRow.getRowNum(), td.getCol(), td.getColBound()));
            //sheet.addMergedRegion(new CellRangeAddress(td.getRow(), td.getRowBound(), td.getCol(), td.getColBound()));

**Comment by liaochong** [comment]
感谢，会在后续版本考虑该方案
