### ISSUE TITLE
excel已清空内容,却读取了空的内容?

### ISSUE THREAD

**Issue by cielswift** [liaochong/myexcel#232]
![image](https://user-images.githubusercontent.com/42295829/79943914-c8644300-849c-11ea-8845-950a2aca024a.png)

第4行以下的内容均被清空了,可是依然读取到了内容; 空字符串

调用了这个方法
 /**
     * 读取处理Excel文件
     * @param clazz 用什么实体类接收
     * @param multipartFile 上传的文件
     * @param consumer 具体的业务逻辑
     * @param <T> 实体类泛型
     * @throws AlertException
     */
    public static <T> void readExcel(Class<T> clazz, MultipartFile multipartFile,
                                     Consumer<T> consumer) throws AlertException {

        try{
            // （推荐）方式二：读取一行处理一行，可自行决定终止条件，SAX模式，避免OOM，建议大量数据使用
            // readThen有两种重写接口，返回Boolean型接口允许在返回False情况下直接终止读取
            SaxExcelReader.of(clazz)
                    .sheet(0) // 获取第一个sheet
                    .rowFilter(row -> row.getRowNum() > 1) // 过滤第0,1行,是标题
                    // .beanFilter(t -> t.getIfTeam().equals(1)) // 根据bean的条件过滤
                    .readThen(multipartFile.getInputStream(),consumer);// 可接收inputStream
        }catch (Exception e){
            throw new AlertException("读取excel失败");
        }
    }

@Override
    @Transactional(rollbackFor = Exception.class)
    public List<Problem> checkAndSave(MultipartFile problem) throws AlertException {

        List<String> lev = sysDictService.getByParent(33);
        List<String> cls = sysDictService.getByParent(29);
        List<String> typ = sysDictService.getByParent(17);

        //不合格的
        List<Problem> failed = new ArrayList<>();

        ExcelImportExportUtils.readExcel(Problem.class, problem, (pro) -> {

            try {
                if (Faster.isNull(pro) || Faster.isNull(pro.getResidentName())) {
                    return;
                }
                Faster.throwNotIn(pro.getDifficultLevel(), lev);
                Faster.throwNotIn(pro.getIndustryCategory(), typ);
                Faster.throwNotIn(pro.getCategory(), cls);

                pro.setId(null);
                saveOrUpdateProblem(pro);

            } catch (Exception e) {
                failed.add(pro);
            }
        });

        return failed;
    }

![image](https://user-images.githubusercontent.com/42295829/79944315-c8b10e00-849d-11ea-91ad-541eb34e5d1e.png)

**Comment by liaochong** [comment]
请提供下版本，该问题3.7.3版本已修复

**Comment by cielswift** [comment]
3.5.1

**Comment by liaochong** [comment]
请升级后查看是否解决

**Comment by cielswift** [comment]
Fail to read xlsx file:i_t_88_1587545437413_27199381814688902406.xlsx

**Comment by cielswift** [comment]
抱着错误

**Comment by cielswift** [comment]
Index cannot be repeated: 12. Please check it.

**Comment by liaochong** [comment]
你设置在字段上的index重复了，有多个index=12

**Comment by liaochong** [comment]
问题是否解决？如解决，该问题将被关闭
