### ISSUE TITLE
请问如何自定义表头？就是我希望生成excel的时候第一行的内容居中然后是我自定义的表头

### ISSUE THREAD

**Issue by lvdong** [liaochong/myexcel#233]
请问如何自定义表头？就是我希望生成excel的时候第一行的内容居中然后是我自定义的表头。然后再下面就是title,数据这些

**Comment by liaochong** [comment]
有两种方式，一种是使用多级表头，另外一种是使用模板+列表导出（流式导出），具体请参考文档
