### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by snail-zz** [liaochong/myexcel#235]
在项目中大量使用，如果楼主可以增加如下功能，则更完美：
1.导入时，增加数据检验，如必填，小数位，是否允许小于0，邮件，电话等,如果能支持自定义校验接口（如判断用户存在）则更好， 
2.导出时，提供excel模板导出(现状是企业开发有大量excel模板)

**Comment by liaochong** [comment]
感谢使用，关于上述几点回复如下：
1. 校验，这个功能在2.8版本考虑过，但后续放弃了，主要是边界问题，myexcel读取的方式提供了配合校验框架的接口，建议配合hibernate-validator，这种目前生产上表明是最佳实践；
2.excel模板问题，有规划excel模板导出功能，但目前受限于myexcel开发人员较少，且需求较多，如复杂属性导入导出等等，所以排期靠后；

鉴于你们在项目中大量使用，最近发布了3.7.5版本，建议尽快升级，该版本修复了两个导入导出比较严重的bug（在特定场景中出现），也欢迎加入myexcel进行开发，如有问题可随时联系，再次感谢使用🙏
