### ISSUE TITLE
怎么动态控制导出列呢?

### ISSUE THREAD

**Issue by cielswift** [liaochong/myexcel#239]
@IgnoreColumn 可以排除某列, 但是其他地方需要导出这一列? 怎么动态控制呢?

**Comment by liaochong** [comment]
@ExcelColumn中有个group属性，你在导出时指定group就可以导出所需分组字段：
DefaultExcelBuilder.of(TestDebugInfo.class).groups(MyGroup.class).build(dataList);

**Comment by cielswift** [comment]
非常感谢,这对我意义重大,我差点就要写poi那些东西了
