### ISSUE TITLE
系统会自动创建一个myExcel的文件价

### ISSUE THREAD

**Issue by wltj920** [liaochong/myexcel#240]
![image](https://user-images.githubusercontent.com/10513736/82025401-e13ecd80-96c3-11ea-94f7-4a9d18381619.png)
如题，不知道为何，系统中总会自动创建这个文件夹

**Comment by liaochong** [comment]
这是正常的，myexcel内所有创建的临时文件都会放在这个文件夹内，方便管理

**Comment by wltj920** [comment]
> 这是正常的，myexcel内所有创建的临时文件都会放在这个文件夹内，方便管理

理解了，但是不能自动删除临时文件夹吗，感觉系统被入侵了一样，突然多了一个文件夹

**Comment by liaochong** [comment]
可以自动删除临时文件夹，但是这是有代价的，在某些情况下，如多个用户同时导入导出，可能会频繁的IO，得不偿失

**Comment by wltj920** [comment]
> 可以自动删除临时文件夹，但是这是有代价的，在某些情况下，如多个用户同时导入导出，可能会频繁的IO，得不偿失

好吧
