### ISSUE TITLE
无法获取当前数据的行数

### ISSUE THREAD

**Issue by qhl100** [liaochong/myexcel#241]
DefaultExcelReader.of(ArtCrowd.class)
        .sheet(0) // 0代表第一个，如果为0，可省略该操作，也可sheet("名称")读取
        .rowFilter(row -> row.getRowNum() > 0) // 如无需过滤，可省略该操作，0代表第一行
        .beanFilter(ArtCrowd::isDance) // bean过滤
        .readThen(path.toFile() ,artCrowd -> {System.out.println(artCrowd.getName);

这里如何确定，当前数据在EXCEL中的第几行？？？
});// 可接收inputStream

**期望的结果**
当前数据在EXCEL中的第几行？？？

**Comment by liaochong** [comment]
当前接口均未提供上下文信息，3.8.0版本将提供，感谢使用

**Comment by liaochong** [comment]
3.8.0版本已发布，readThen接口提供上下文，上下文包含行数，如readThen(file , (obj , context)->{

})
