### ISSUE TITLE
导入时使用title进行解析，日期变成了数字

### ISSUE THREAD

**Issue by li873582595** [liaochong/myexcel#242]
导入excel的解析类中的日期字段：
`@ExcelColumn(title = "刊登日期", dateFormatPattern = "yyyy-MM-dd HH:mm:ss")
 private String startTime;`
解析工具如下：
`resultList = SaxExcelReader.of(EbayImportProductEntity.class)
                    .sheet(0)
                    .rowFilter(row -> row.getRowNum() > 0)
                    .read(MyFileUtils.getFile(filePath));`

解析的结果集中日期为 43942.9654398148，excel中的原始日期为2020/4/21 23:10:14

**Comment by liaochong** [comment]
数字是excel保存日期的一种格式，从excel中解析得到的文本就是这种格式，所以如果用string来接收出现这种情况是正常的，如需获得正确格式，建议使用Date或者LocalDateTime接收

**Comment by li873582595** [comment]
好的，回头试试，谢谢啦


祝身体健康，工作顺利！
**********************************
李志勇
Tel：18337629976
Email： lizhiyong873582595@126.com
QQ：873582595


在2020年5月22日 15:54，清沐<notifications@github.com> 写道：

数字是excel保存日期的一种格式，从excel中解析得到的文本就是这种格式，所以如果用string来接收出现这种情况是正常的，如需获得正确格式，建议使用Date或者LocalDateTime接收
