### ISSUE TITLE
在3.0.1版本中导出使用 dateFormatPattern 自定义日期格式不起作用，@ExcelColumn(title = "作废日期", style={"title->vertical-align:middle; text-align:center", "cell->vertical-align:middle; text-align:center"}, dateFormatPattern = "yyyy年MM月dd日", width = 13)     private String repealTime;

### ISSUE THREAD

**Issue by Talentime** [liaochong/myexcel#243]
**Bug描述**
描述Bug产生的现象（A clear and concise description of what the bug is.）

**Bug复现**
按如下步骤复现（Steps to reproduce the behavior）:

**期望的结果**
期望的结果是什么（A clear and concise description of what you expected to happen.）

**Comment by liaochong** [comment]
dateFormatPattern针对的是时间类型，如Date、LocalDateTime等，字符串无效
