### ISSUE TITLE
HTML图片模板建议

### ISSUE THREAD

**Issue by SpaceZL** [liaochong/myexcel#245]
**现状**
1.导入图片，需要格外存储图片路径，绝对路径
2.图片大小只能填充当前单元格，且无法填充合并后的单元格

**期望的结果**
1.小图片使用BASE64
2.img标签，使用width，height属性 设置resize缩放

**Comment by liaochong** [comment]
感谢，后续版本考虑加入

**Comment by nian8** [comment]
有这需求

**Comment by liaochong** [comment]
4.1.0版本支持http、base64图片导出，支持填充合并后单元格
