### ISSUE TITLE
下拉列表能否支持从数据字典取值

### ISSUE THREAD

**Issue by jacky8466** [liaochong/myexcel#253]
excel表格中的下拉列表数据，能否支持动态从数据字典里取值，因为很多数据的类型都是在数据字典里定义的，而且会不定期新增

**Comment by liaochong** [comment]
excel表格中的下拉列表并不限制数据来源以及方式，来源与方式是由开发者自行决定的，但如果你的意思是导出的excel会主动更新下拉列表信息的话，这无法实现

**Comment by jacky8466** [comment]
> excel表格中的下拉列表并不限制数据来源以及方式，来源与方式是由开发者自行决定的，但如果你的意思是导出的excel会主动更新下拉列表信息的话，这无法实现

可能是我表述的不清楚，我来描述下我的场景：
用户导入数据的excel模板是用户控制的，
用户在前端选择想要导入哪些字段，沟选好后，再点击下载模板，系统动态生成excel模板，如果里面涉及到状态，或者枚举值的，比如性别：男，女(我是在数据字典里维护的)，在模板里相应字段里生成下拉选项。
我根据官方的示例https://github.com/liaochong/myexcel/wiki/%E4%B8%8B%E6%8B%89%E5%88%97%E8%A1%A8，不太清楚怎么操作，我也尝试了，但结果都不是我想要的

**Comment by liaochong** [comment]
![image](https://user-images.githubusercontent.com/8674986/85199710-479eb780-b324-11ea-889d-8a8aa91966f8.png)
不是你想要的？能具体些吗？是无法生成下拉列表？
