### ISSUE TITLE
Map导出能否支持设置format

### ISSUE THREAD

**Issue by daihy8759** [liaochong/myexcel#256]
如题，好像Map的导出没办法设置format，这个属性可以暴露出来手动设置吗
![image](https://user-images.githubusercontent.com/6057326/86106239-e41a4400-baf2-11ea-9090-1b1dfca8cd5e.png)

**Comment by liaochong** [comment]
抱歉，暂不支持，需要主动设置好格式，如果是clone，可以自行增加formats方法处理
