### ISSUE TITLE
如何自定义标题

### ISSUE THREAD

**Issue by yidasanqian** [liaochong/myexcel#259]
第一行是标题居中
第二行开始是列名
第三行是列对应的值

有案例吗

**Comment by liaochong** [comment]
请参照多级表头&流式导出：
https://github.com/liaochong/myexcel/wiki/multiple-title
https://github.com/liaochong/myexcel/wiki/Excel%E6%B5%81%E5%BC%8F%E5%AF%BC%E5%87%BA

**Comment by yidasanqian** [comment]
> 请参照多级表头&流式导出：
> https://github.com/liaochong/myexcel/wiki/multiple-title
> https://github.com/liaochong/myexcel/wiki/Excel%E6%B5%81%E5%BC%8F%E5%AF%BC%E5%87%BA

每列都要像这样定义吗
```
@ExcelColumn(title="标题->年龄")
Integer age
@ExcelColumn(title="标题->年龄")
String name
```

title可以动态设置吗

**Comment by liaochong** [comment]
可以动态设置，请使用titles方法，如DefaultExcelBuilder.of(X.class).titles(List<>)

**Comment by yidasanqian** [comment]
<img width="251" alt="Screen Shot 2020-07-16 at 22 59 40" src="https://user-images.githubusercontent.com/10655188/87687279-22348a80-c7b8-11ea-9952-bd3e3fa7a288.png">

像这样的。titles要怎么设置？

下面这样对吗
```
        List<String> titles = new ArrayList<>();
        titles.add("联系人");
        titles.add("联系人->姓名");
        titles.add("联系人->电话1");
        titles.add("联系人->电话2");
```

**Comment by liaochong** [comment]
是的

**Comment by yidasanqian** [comment]
上面动态的标题怎么设置样式，调整列宽、换行、行高，背景？

**Comment by liaochong** [comment]
有对应的方法，widths()、style()，样式包含了列宽、行高、背景，参照css样式，换行加入\\n即可

**Comment by yidasanqian** [comment]
模版导出和注解导出哪个性能更高？

**Comment by liaochong** [comment]
尽量使用注解导出，模板导出适合复杂布局导出

**Comment by yidasanqian** [comment]
> 尽量使用注解导出，模板导出适合复杂布局导出

如果要支持动态标题的话是不是就不支持注解导出？
