### ISSUE TITLE
CSV读取问题 - 遇到单元格带有换行符 - 导致无法正常读取

### ISSUE THREAD

**Issue by github291406933** [liaochong/myexcel#264]
这是csv文件内容
![image](https://user-images.githubusercontent.com/11879494/89971877-075a1680-dc8f-11ea-8de1-58fb7e85cb6d.png)

这是调试代码读到“一行”数据
![image](https://user-images.githubusercontent.com/11879494/89971913-15a83280-dc8f-11ea-8316-afcbd5cc4c34.png)

**Comment by liaochong** [comment]
目前myexcle中csv读取功能比较简单，建议使用apache commons csv读取，后续myexcel会集成commons csv

**Comment by liaochong** [comment]
4.0.0.RC1修复该问题
