### ISSUE TITLE
excel直接作为模板他不香吗？？？比整什么各种模板代码省多少事？？？？

### ISSUE THREAD

**Issue by zxiaozhou** [liaochong/myexcel#270]
能否支持excel作为模板，没有什么比用excel配置为模板方便的了，所见所得，还省了一大堆去写模板代码，，这个要是叫实施自己定义个模板都难，，全部压开发、写代码

**Comment by lvdong** [comment]
是的。强烈建议能增加这个功能

**Comment by liaochong** [comment]
MyExcel的核心功能是导出海量数据以及高复杂度表格导出，且限于人力&精力有限，短时间内无法提供Excel模板导出，请见谅，可配合其他优秀Excel模板导出工具（如jxls）使用，后续会尽快Excel模板导出提上开发日程
