### ISSUE TITLE
不能像jxls那样用excel模板导出吗?

### ISSUE THREAD

**Issue by mostcool** [liaochong/myexcel#274]
像下图这样导出
![image](https://user-images.githubusercontent.com/2172570/93036399-57534100-f672-11ea-9a97-3d83c3799921.png)

**Comment by liaochong** [comment]
暂时不能，小数据情况下可配合jxls导出

**Comment by mostcool** [comment]
> 暂时不能，小数据情况下可配合jxls导出

@liaochong 有计划支持不?

**Comment by liaochong** [comment]
MyExcel的核心功能是导出海量数据以及高复杂度表格导出，且限于人力&精力有限，短时间内无法提供Excel模板导出，请见谅，后续会尽快Excel模板导出提上开发日程
