### ISSUE TITLE
样式设置问题cell->color:green不生效

### ISSUE THREAD

**Issue by weiweili666** [liaochong/myexcel#275]
使用DefaultExcelBuilder导出，想要对导出excel 的title和cell添加样式，使用如下编码，cell->color:green不生效：
 Workbook workbook = DefaultExcelBuilder.of(Map.class)
                .sheetName("sheet1")
                .widthStrategy(WidthStrategy.COMPUTE_AUTO_WIDTH)
                .noStyle()
                .style("title->text-align:center", "cell->text-align:center","cell->color:green;")
                .titles(titles)
                .fieldDisplayOrder(orders)
                .build(data);

**Comment by 18256086350** [comment]
.style("title->color:red","text-align:center;","background-color:green;") 中间的"text-align:center;"不生效

**Comment by liaochong** [comment]
请先升级为最新版：3.9.5

**Comment by 18256086350** [comment]
版本是3.9.5，最新版本

**Comment by liaochong** [comment]
![image](https://user-images.githubusercontent.com/8674986/93193961-1a727180-f77a-11ea-9d64-dcf40aa9ad93.png)

**Comment by 18256086350** [comment]
我将该.noStyle()注释掉，也是不行，中间cell->text-align:center 还是不生效，是不是.style()方法只支持2个样式?

**Comment by liaochong** [comment]
并没有这种限制，可能存在bug，你可以试试这样写：.style("title->text-align:center", "cell->text-align:center;color:green;")

**Comment by 18256086350** [comment]
OK了，谢谢大佬
