### ISSUE TITLE
DefaultExcelReader .readThen 按照提供的解决思路还是报错

### ISSUE THREAD

**Issue by KiDddder** [liaochong/myexcel#276]
[ERROR] /home/saas/.jenkins/workspace/F-hgz-customer-rest/hgz-customer-rest/src/main/java/com/cargopm/hgz/customer/cilents/excel/ExcelClient.java:[53,21] reference to readThen is ambiguous
  both method readThen(java.io.InputStream,java.util.function.Consumer<T>) in com.github.liaochong.myexcel.core.DefaultExcelReader and method 

场景：我本地打包、执行都是正常的。在Jenkins(linux) 上打包就会报上面的错

**Comment by KiDddder** [comment]
DefaultExcelReader.of(BookingExcelDto.class)
                    .rowFilter(row -> row.getRowNum() == 5)
                    .readThen(fis, data -> {
                        System.out.println(data);
                    });

**Comment by liaochong** [comment]
理论上本地打包和jenkins是一样的，你先改成以下代码试试：
SaxExcelReader.of(BookingExcelDto.class)
.rowFilter(row -> row.getRowNum() == 5)
.readThen(fis, data -> {
System.out.println(data);
});

**Comment by KiDddder** [comment]
也报了上面一样的错。版本已经升到了3.9.5

**Comment by liaochong** [comment]
SaxExcelReader.of(BookingExcelDto.class)
.rowFilter(row -> row.getRowNum() == 5)
.readThen(fis, data -> {
System.out.println(data);
return true;
});

**Comment by KiDddder** [comment]
DefaultExcelReader.of(BookingExcelDto.class)
                    .rowFilter(row -> row.getRowNum() == 5)
                    .readThen(fis, data -> {
                        atomicReference.set(HgzOrderDTO.builder().shipper(data.getShipper()).consignee(data.getConsignee()).importer(data.getImporter()).build());
                        return false;
                    });这样会报错

**Comment by KiDddder** [comment]
我现在强制定义拉姆达的入参类型
DefaultExcelReader.of(BookingExcelDto.class)
                    .rowFilter(row -> row.getRowNum() == 5)
                    .readThen(fis, (BookingExcelDto data) -> {
                        atomicReference.set(HgzOrderDTO.builder().shipper(data.getShipper()).consignee(data.getConsignee()).importer(data.getImporter()).build());
                    });
这样可以了
