### ISSUE TITLE
多sheet读取

### ISSUE THREAD

**Issue by xuli1266** [liaochong/myexcel#278]
有2个问题麻烦赐教
1. 多sheet读取如何获取sheet名称
2. 多sheet中内容都是不同的
List<Map> mapList = SaxExcelReader.of(Map.class).readAllSheet().read(inputStream);
使用以上方法只能将所有内容合并到一个list<Map>
想要的结果:
list<list,Map> 最好是List<List,T >  该如何做?

**Comment by xuli1266** [comment]
自己解决了, 脑子没转过弯, 类似如下
public ResultVo<Long> upload(String url) {
        try (InputStream inputStream = Utils.fileDownload(url)) {
            inputStream.mark(0);
            XSSFWorkbook wb = new XSSFWorkbook(inputStream);
            Iterator<Sheet> sheets = wb.iterator();
            int i = 0;
            while (sheets.hasNext()) {
                Sheet sheet = sheets.next();
                inputStream.reset();
                Class<? extends MmsRebateUploadDto> type = getClassType(sheet.getSheetName());
                List<? extends MmsRebateUploadDto> dataList = DefaultExcelReader.of(type)
                        .sheet(i)
                        .rowFilter(row -> row.getRowNum() > 0)
                        .read(inputStream);
                i++;
            }
          /*  if (CollectionUtils.isEmpty(resultList)) {
                throw new ParamsException("文件读取错误");
            }*/
        } catch (Exception e) {
            log.error("MmsRebateServiceImpl.upload error url:{}", url, e);
            throw new ParamsException("文件读取错误");
        }
        return null;
    }

**Comment by liaochong** [comment]
3.9.6版本DefaultExcelReader、SaxExcelReader新增了startSheet方法，里面可以获取当前sheet的信息，如：
DefaultExcelReader.of(type)
.sheet(i)
.startSheet(sheet->sheet.getName())
.rowFilter(row -> row.getRowNum() > 0)
.read(inputStream);
