### ISSUE TITLE
Beetil3.2.2 NoSuchMethodError

### ISSUE THREAD

**Issue by chenhahahahaha** [liaochong/myexcel#286]
**Bug描述**
程序使用的是beetl 3.x版本(无法降级) 在使用myexcel3.9.9 想做excel导出时报错
```
java.lang.NoSuchMethodError: org.beetl.core.GroupTemplate.getTemplate(Ljava/lang/String;)Lorg/beetl/core/Template;
	at com.github.liaochong.myexcel.core.templatehandler.BeetlTemplateHandler.setTemplateEngine(BeetlTemplateHandler.java:45) ~[myexcel-3.9.9.jar:na]
	at com.github.liaochong.myexcel.core.templatehandler.AbstractTemplateHandler.classpathTemplate(AbstractTemplateHandler.java:40) ~[myexcel-3.9.9.jar:na]
```
**Bug复现**
按如下步骤复现（Steps to reproduce the behavior）:
1.  项目的jar 版本  
        <dependency>
            <groupId>com.ibeetl</groupId>
            <artifactId>sql-springboot-starter</artifactId>
            <version>3.0.9-RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.github.liaochong</groupId>
            <artifactId>myexcel</artifactId>
            <version>3.9.9</version>
        </dependency>
2. 使用master分支的example项目, 将
        <dependency>
            <groupId>com.ibeetl</groupId>
            <artifactId>beetl</artifactId>
            <version>2.9.9</version>
        </dependency>
替换成
        <dependency>
            <groupId>com.ibeetl</groupId>
            <artifactId>sql-springboot-starter</artifactId>
            <version>3.0.9-RELEASE</version>
        </dependency>
调用
BeetlExcelBuilderExampleController.buildWithSXLSX
可以复现

***尝试办法***
重写了BeetlTemplateHandler和BeetlExcelBuilder 在 BeetlExcelBuilder中
    public MyBeetlExcelBuilder() {
        super(MyBeetlTemplateHandler.class);
    }
出现Cannot be accessed from outside package

**Comment by liaochong** [comment]
3.9.9版本，采用beetl 3.2.4.RELEASE最新版，未出现描述问题
![Uploading image.png…]()

**Comment by liaochong** [comment]
3.2.2.RELEASE版本beetl作者移除了某些方法，后续版本又兼容上了，建议单独升级下beetl版本为3.2.4.RELEASE，3.9.10版本将修复自定义ExcelBuilder outside package问题

**Comment by liaochong** [comment]
3.9.10版本已发布，预计2020-11-22可用，感谢使用！！！
