### ISSUE TITLE
mappingConvert 能否支持自定义呢

### ISSUE THREAD

**Issue by lishidetainan** [liaochong/myexcel#292]
根据文档 mapping 目前只支持DefaultStreamBuilder, DefaultBuilder 如果自己扩展继承的话不是特别方便，有个场景，很多mapping 都是从数据库读取的 。而且可能实时变化的，能否支持一下用户自定义扩展的mappingConvert呢 谢谢

**Comment by liaochong** [comment]
下一版本支持，感谢使用

**Comment by liaochong** [comment]
3.11.6版本支持自定义转化，参见：https://github.com/liaochong/myexcel/wiki/%E5%86%99%E5%85%A5%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BD%AC%E5%8C%96
