### ISSUE TITLE
默认导出style weight生效height 设置失效

### ISSUE THREAD

**Issue by lezhangc** [liaochong/myexcel#294]
默认导出style weight生效height 设置失效

**Comment by liaochong** [comment]
具体样式设置，以及版本

**Comment by lezhangc** [comment]
版本3.9.11，
![S1S`ECJGG6RN3 N10K}HIR](https://user-images.githubusercontent.com/20539210/103068514-406ca500-45f8-11eb-9400-8d3dbb7f18ae.png)

**Comment by lezhangc** [comment]
Workbook workbook = DefaultExcelBuilder.of(EmployeeDTO.class).style("height:150px").build(employeeDTOList);

**Comment by lezhangc** [comment]
Workbook workbook = DefaultExcelBuilder.of(EmployeeDTO.class).style("height:150px").build(employeeDTOList);
Workbook workbook = DefaultExcelBuilder.of(EmployeeDTO.class).style("cell->height:150px").build(employeeDTOList);
版本号：3.9.11

**Comment by liaochong** [comment]
DefaultExcelBuilder.of(EmployeeDTO.class).rowHeight(150).build(employeeDTOList)
