### ISSUE TITLE
The maximum length of cell contents (text) is 32767 characters

### ISSUE THREAD

**Issue by 18256086350** [liaochong/myexcel#297]
hello，
    当导出的某个字段值非常大的时候，超过32767 characters，poi会报错，java.lang.IllegalArgumentException: The maximum length of cell contents (text) is 32767 characters;查找了部分资料，说是可以重写org.apache.poi.ss.SpreadsheetVersion 中
EXCEL2007(0x100000, 0x4000, 255, Integer.MAX_VALUE, 64000, 32767);  32767改写为Integer.MAX_VALUE。修改后excel可以正常生成，但是在打开的时候，会提示excel存在错误，是否信任打开。打开后发现字段被截断了，并不是完整展示。
  对于这个问题，不知道您可知道是否有办法解决？谢谢！

**Comment by liaochong** [comment]
excel单元格数据长度是excel本身限制的，不建议修改
