### ISSUE TITLE
xlsx另存为xls会读取到空行

### ISSUE THREAD

**Issue by crgoodjob** [liaochong/myexcel#298]
xlsx文件中有2行数据，最后还有3行无数据，但是有样式黑边框。read()数据时，可以读取到2行数据没问题。
但是若将此文件另存为xls时，再次read()数据时，会读取到5行数据，包括另外三行空行（黑边框）数据

**Comment by liaochong** [comment]
能提供下源文件吗？方便复现

**Comment by crgoodjob** [comment]
[777.xlsx](https://github.com/liaochong/myexcel/files/5855510/777.xlsx)

**Comment by liaochong** [comment]
保存后，多出空行的问题无法直接解决，3.11.6版本新增ignoreBlankRow方法，可忽略空行
