### ISSUE TITLE
EXCEL导入时rowFilter、beanFilter问题

### ISSUE THREAD

**Issue by wangyh2650** [liaochong/myexcel#299]
使用SaxExcelReader导入excel时加入rowFilter时发现同一行会重复多次进入rowFilter方法，rowFilter中返回false时会继续处理该行的cell，且再次执行rowFilter。
这个能否改为filter返回false时不再处理该行的cell，减少重复执行？

**Comment by liaochong** [comment]
返回false，是不处理，另外同一行只会处理一次，确定是同一行？

**Comment by wangyh2650** [comment]
> 返回false，是不处理，另外同一行只会处理一次，确定是同一行？

确定同一行返回false后还会继续处理该行的cell

**Comment by liaochong** [comment]
SaxExcelReader导入，默认是以单元格作为处理单元，所以同一行会调用多次，不影响实际数据，后续如果可能进行优化
