### ISSUE TITLE
excel自动列宽设置

### ISSUE THREAD

**Issue by weiweili666** [liaochong/myexcel#311]
您好，请教一下个问题：
        导出excel，采用COMPUTE_AUTO_WIDTH，自动计算单元格列宽，还是会出现一列不够，会占用后面的空格列（如果该列的值很长的话）。
        我目前采用的是自动换行，保证在一列里展示，但是不是那么的美观。

请问，不知有没有能够实现展示这种很长的列值的方法。

**Comment by liaochong** [comment]
使用AUTO_WIDTH试试，但这种会影响性能

**Comment by weiweili666** [comment]
试了一下，有报错 SXSSF does not support automatic width at this time。SXSSF  不支持 AUTO_WIDTH？

**Comment by liaochong** [comment]
需要改成XSSF模式
