### ISSUE TITLE
表格居中有问题

### ISSUE THREAD

**Issue by ryuhi** [liaochong/myexcel#312]
**Bug描述**
使用的版本
`        <dependency>
            <groupId>com.github.liaochong</groupId>
            <artifactId>myexcel</artifactId>
            <version>3.9.7</version>
        </dependency>

        <dependency>
            <groupId>com.ibeetl</groupId>
            <artifactId>beetl</artifactId>
            <version>2.9.9</version>
        </dependency>`

在tr标签中加居中设置，但是在循环中加判断条件的部分中，就会有问题，还是居左，不是居中。

`                    <% if (k > 0) { %>
                        <tr style="text-align: center; border-style:thin; vertical-align: center;">
                    <% } %>`

像这样的就不行

效果类似这样
![image](https://user-images.githubusercontent.com/3222788/115834510-e4038000-a447-11eb-9082-cbc7159210c1.png)

**Bug复现**
按如下步骤复现（Steps to reproduce the behavior）:
1.编写bettl模板，模板中，有循环，循环中有判断，判断的内容中包含上述代码
2. 导出excel文件

**期望的结果**
能正确居中

**Comment by liaochong** [comment]
最后生成的html文件样式设置正确吗？

**Comment by ryuhi** [comment]
> 最后生成的html文件样式设置正确吗？

我中间没有生成html文件啊，只有最后的excel文件

**Comment by liaochong** [comment]
使用beetl，实际上会生成一份html内容文件，你可以看下内容是不是正确的，这种大概率是因为实际生成的html内容样式设置有问题，如果你不确定的话，可以用一份写死（内容居中）的bettl文件来验证

**Comment by ryuhi** [comment]
> 使用beetl，实际上会生成一份html内容文件，你可以看下内容是不是正确的，这种大概率是因为实际生成的html内容样式设置有问题，如果你不确定的话，可以用一份写死（内容居中）的bettl文件来验证

大佬你知道那个html文件在哪里能看到吗？提示下，我去看看

**Comment by liaochong** [comment]
用一份写死（内容居中）的bettl文件来验证下是不是可以正常居中吧，要么你断点进去查看流，稍微麻烦些

**Comment by ryuhi** [comment]
> 用一份写死（内容居中）的bettl文件来验证下是不是可以正常居中吧，要么你断点进去查看流，稍微麻烦些

sorry，是我的问题，和myexcel、beetl无关，大佬把这个clos掉吧
