### ISSUE TITLE
[ERROR] [2021-05-06 16:25:54] org.apache.poi.hssf.usermodel.HSSFCellStyle.setAlignment(Lorg/apache/poi/ss/usermodel/HorizontalAlignment;)V

### ISSUE THREAD

**Issue by biankobe24** [liaochong/myexcel#314]
myexcel最新版本，poi版本4.1.1，4.1.2都试过了，一直报这个错，编译的时候没问题。请问下这个怎么解决

**Comment by liaochong** [comment]
这个一般是poi版本冲突了，需要确认下你的poi全部版本，可以用dependencymanagement设置

**Comment by biankobe24** [comment]
> 这个一般是poi版本冲突了，需要确认下你的poi全部版本，可以用dependencymanagement设置

就一个MyExcel啊，poi依赖都是用的里面的

**Comment by biankobe24** [comment]
> 这个一般是poi版本冲突了，需要确认下你的poi全部版本，可以用dependencymanagement设置

就一个MyExcel啊，poi依赖都是用的里面的

**Comment by liaochong** [comment]
如果使用IDEA，可以使用maven helper插件查看，或者直接查看当前应用依赖是否包含其他版本POI，这种可能是其他依赖引入的，非你直接依赖

**Comment by biankobe24** [comment]
` <dependencies>
        <dependency>
            <groupId>aopalliance</groupId>
            <artifactId>aopalliance</artifactId>
            <version>${aopalliance.version}</version>
        </dependency>
        <dependency>
            <groupId>org.attoparser</groupId>
            <artifactId>attoparser</artifactId>
            <version>${attoparser.version}</version>
        </dependency>
        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>bson</artifactId>
            <version>${mongodb.bson.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-beanutils</groupId>
            <artifactId>commons-beanutils</artifactId>
            <version>${commons.beanutils.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>${commons.codec.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-fileupload</groupId>
            <artifactId>commons-fileupload</artifactId>
            <version>${commons.fileupload.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>${commons.io.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>${commons.lang.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-logging</groupId>
            <artifactId>commons-logging</artifactId>
            <version>${commons.logging.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-net</groupId>
            <artifactId>commons-net</artifactId>
            <version>${commons.net.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-pool2</artifactId>
            <version>${org.apache.commons.pool2.version}</version>
        </dependency>
        <dependency>
            <groupId>dom4j</groupId>
            <artifactId>dom4j</artifactId>
            <version>${dom4j.version}</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid</artifactId>
            <version>${com.alibaba.druid.version}</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>${com.alibaba.fastjson.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.ethz.ganymed</groupId>
            <artifactId>ganymed-ssh2</artifactId>
            <version>${ch.ethz.ganymed.ganymed.ssh2.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${com.fasterxml.jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${com.fasterxml.jackson.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>jackson-annotations</artifactId>
                    <groupId>com.fasterxml.jackson.core</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>${com.fasterxml.jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.auth0</groupId>
            <artifactId>java-jwt</artifactId>
            <version>${com.auth0.java.jwt.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>commons-codec</artifactId>
                    <groupId>commons-codec</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>jackson-databind</artifactId>
                    <groupId>com.fasterxml.jackson.core</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>javax.mail</groupId>
            <artifactId>javax.mail-api</artifactId>
            <version>${javax.mail.version}</version>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>${javax.servlet.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jfree</groupId>
            <artifactId>jcommon</artifactId>
            <version>${jfree.jcommon.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>gnujaxp</groupId>
                    <artifactId>gnujaxp</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>${redis.clients.jedis.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>commons-pool2</artifactId>
                    <groupId>org.apache.commons</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>slf4j-api</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.jfree</groupId>
            <artifactId>jfreechart</artifactId>
            <version>${org.jfree.jfreechart.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>xml-apis</artifactId>
                    <groupId>xml-apis</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.jcraft</groupId>
            <artifactId>jsch</artifactId>
            <version>${com.jcraft.jsch.version}</version>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongo-java-driver</artifactId>
            <version>${org.mongodb.mongo.java.driver.version}</version>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus</artifactId>
            <version>${com.baomidou.mybatis.plus.version}</version>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-core</artifactId>
            <version>${com.baomidou.mybatis.plus.version}</version>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-annotation</artifactId>
            <version>${com.baomidou.mybatis.plus.version}</version>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-extension</artifactId>
            <version>${com.baomidou.mybatis.plus.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${org.slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>${org.slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-aop</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
            <version>${spring.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>commons-logging</artifactId>
                    <groupId>commons-logging</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-redis</artifactId>
            <version>${org.springframework.data.spring.data.redis.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>slf4j-api</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-aop</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-beans</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-context</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-core</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-tx</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-expression</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-jdbc</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-messaging</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-tx</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-websocket</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.sshd</groupId>
            <artifactId>sshd-core</artifactId>
            <version>${org.apache.sshd.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>slf4j-api</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.thymeleaf</groupId>
            <artifactId>thymeleaf</artifactId>
            <version>${org.thymeleaf.version}</version>
        </dependency>
        <dependency>
            <groupId>org.thymeleaf</groupId>
            <artifactId>thymeleaf-spring4</artifactId>
            <version>${org.thymeleaf.version}</version>
        </dependency>
        <dependency>
            <groupId>org.unbescape</groupId>
            <artifactId>unbescape</artifactId>
            <version>${org.unbescape.unbescape.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity</artifactId>
            <version>${org.apache.velocity.version}</version>
        </dependency>
        <dependency>
            <groupId>com.101tec</groupId>
            <artifactId>zkclient</artifactId>
            <version>${com.101tec.zkclient.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>log4j</artifactId>
                    <groupId>log4j</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>zookeeper</artifactId>
                    <groupId>org.apache.zookeeper</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper</artifactId>
            <version>${org.apache.zookeeper.version}</version>
            <type>pom</type>
            <exclusions>
                <exclusion>
                    <artifactId>junit</artifactId>
                    <groupId>junit</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>log4j</artifactId>
                    <groupId>log4j</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>slf4j-api</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>slf4j-log4j12</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
            <version>${com.github.ben.manes.caffeine.version}</version>
        </dependency>
        <dependency>
            <groupId>com.wiscom.unms</groupId>
            <artifactId>Kingbasejdbc4</artifactId>
            <version>${com.wiscom.unms.kingbasejdbc4.version}</version>
        </dependency>
        <dependency>
            <groupId>com.wiscom.unms</groupId>
            <artifactId>dcloud.display.card</artifactId>
            <version>${com.wiscom.unms.dcloud.display.card.version}</version>
        </dependency>
        <dependency>
            <groupId>com.wiscom.unms</groupId>
            <artifactId>unms-basic</artifactId>
            <version>${com.wiscom.unms.basic.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>bcprov-jdk15on</artifactId>
                    <groupId>org.bouncycastle</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>log4j</artifactId>
                    <groupId>log4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.wiscom.unms</groupId>
            <artifactId>autocard</artifactId>
            <version>${com.wiscom.unms.autocard.varsion}</version>
        </dependency>
        <dependency>
            <groupId>com.wiscom.unms</groupId>
            <artifactId>ServiceBusInner</artifactId>
            <version>${com.wiscom.unms.serviceBusInner.varsion}</version>
        </dependency>
        <dependency>
            <groupId>com.wiscom.unms</groupId>
            <artifactId>harbortek-SecurityTools</artifactId>
            <version>${com.wiscom.unms.harbortek.securitytools.version}</version>
        </dependency>
        <dependency>
            <groupId>com.wiscom.unms</groupId>
            <artifactId>org.json</artifactId>
            <version>${com.wiscom.unms.org.json.version}</version>
        </dependency>
        <dependency>
            <groupId>com.wiscom.unms</groupId>
            <artifactId>ExcelUtils</artifactId>
            <version>${com.wiscom.unms.excelutils.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${org.apache.commons.lang3.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-collections4</artifactId>
            <version>${org.apache.commons.collections4.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.liaochong</groupId>
            <artifactId>myexcel</artifactId>
            <version>3.11.4</version>
            <exclusions>
                <exclusion>
                    <artifactId>commons-codec</artifactId>
                    <groupId>commons-codec</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>slf4j-api</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>xmlbeans</artifactId>
                    <groupId>org.apache.xmlbeans</groupId>
                </exclusion>
            </exclusions>
        </dependency>

    </dependencies>`
这个用maven helper排除过了

**Comment by liaochong** [comment]
如果dependencyManagment设置了全局poi版本为4.1.1还是有问题，麻烦把整个异常栈、导出代码贴一下

**Comment by biankobe24** [comment]
> 如果dependencyManagment设置了全局poi版本为4.1.1还是有问题，麻烦把整个异常栈、导出代码贴一下

 // 创建单元格样式
                HSSFCellStyle style = workbook.createCellStyle();
                style.setFont(font);
                style.setAlignment(HorizontalAlignment.CENTER);
                style.setVerticalAlignment(VerticalAlignment.CENTER);
                style.setBorderBottom(BorderStyle.THIN); // 下边框
                style.setBorderLeft(BorderStyle.THIN);// 左边框
                style.setBorderTop(BorderStyle.THIN);// 上边框
                style.setBorderRight(BorderStyle.THIN);// 右边框
第一个设置字体就没问题，下面设置居中就报错了。。java.lang.NoSuchMethodError: org.apache.poi.hssf.usermodel.HSSFCellStyle.setAlignment(Lorg/apache/poi/ss/usermodel/HorizontalAlignment;)V

**Comment by biankobe24** [comment]
0 = {StackTraceElement@11506} "com.wiscom.reportCenter.service.impl.PeriodicTaskServiceImpl.exportNewSafetyComplianceReport(PeriodicTaskServiceImpl.java:6856)"
1 = {StackTraceElement@11507} "com.wiscom.reportCenter.action.ReportExportAction.exportNewSafetyComplianceReport(ReportExportAction.java:158)"
2 = {StackTraceElement@11508} "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
3 = {StackTraceElement@11509} "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
4 = {StackTraceElement@11510} "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
5 = {StackTraceElement@11511} "com.zeroturnaround.jrebelbase.facade.Forward.methodInvoke(SourceFile:244)"
6 = {StackTraceElement@11512} "java.lang.reflect.Method.invoke(Method.java:498)"
7 = {StackTraceElement@11513} "com.wiscom.framework.util.ReflectionUtils.invoke(ReflectionUtils.java:34)"
8 = {StackTraceElement@11514} "com.wiscom.framework.action.RequestProcessor.invokeAction(RequestProcessor.java:180)"
9 = {StackTraceElement@11515} "com.wiscom.framework.action.RequestProcessor.doProcess(RequestProcessor.java:81)"
10 = {StackTraceElement@11516} "com.wiscom.framework.action.RequestProcessor.process(RequestProcessor.java:37)"
11 = {StackTraceElement@11517} "com.wiscom.framework.action.ActionServlet.process(ActionServlet.java:31)"
12 = {StackTraceElement@11518} "com.wiscom.framework.action.ActionServlet.doPost(ActionServlet.java:27)"
13 = {StackTraceElement@11519} "com.wiscom.framework.action.ActionServlet.doGet(ActionServlet.java:22)"
14 = {StackTraceElement@11520} "javax.servlet.http.HttpServlet.service(HttpServlet.java:624)"
15 = {StackTraceElement@11521} "javax.servlet.http.HttpServlet.service(HttpServlet.java:731)"
16 = {StackTraceElement@11522} "org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)"
17 = {StackTraceElement@11523} "org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)"
18 = {StackTraceElement@11524} "org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
19 = {StackTraceElement@11525} "org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)"
20 = {StackTraceElement@11526} "org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)"
21 = {StackTraceElement@11527} "com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)"
22 = {StackTraceElement@11528} "org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)"
23 = {StackTraceElement@11529} "org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)"
24 = {StackTraceElement@11530} "org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)"
25 = {StackTraceElement@11531} "org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
26 = {StackTraceElement@11532} "org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)"
27 = {StackTraceElement@11533} "org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)"
28 = {StackTraceElement@11534} "org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)"
29 = {StackTraceElement@11535} "org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:110)"
30 = {StackTraceElement@11536} "org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:41002)"
31 = {StackTraceElement@11537} "org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)"
32 = {StackTraceElement@11538} "org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)"
33 = {StackTraceElement@11539} "org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)"
34 = {StackTraceElement@11540} "org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)"
35 = {StackTraceElement@11541} "org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)"
36 = {StackTraceElement@11542} "org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)"
37 = {StackTraceElement@11543} "org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)"
38 = {StackTraceElement@11544} "org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)"
39 = {StackTraceElement@11545} "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
40 = {StackTraceElement@11546} "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
41 = {StackTraceElement@11547} "org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
42 = {StackTraceElement@11548} "java.lang.Thread.run(Thread.java:748)"
