### ISSUE TITLE
多级表头导出excel

### ISSUE THREAD

**Issue by weiweili666** [liaochong/myexcel#315]
你好，请问使用多级表头导出excel，列宽使用compute_auto_width,  导出的结果会发现第一列的列宽会很宽，就如下图一样
![Snipaste_2021-05-11_15-27-15](https://user-images.githubusercontent.com/20219409/117775986-9ff8e380-b26d-11eb-8d8d-bbecf431049d.png)
请问这个问题该怎么解决？
谢谢！

**Comment by liaochong** [comment]
这可能是一个bug，麻烦提供下版本号，如比较紧急，可以单独设置第一列宽度

**Comment by liaochong** [comment]
@ExcelColumn(index = 0,width = )
