### ISSUE TITLE
多级标题时对二级标题中的某一个标题设置样式，注解方式

### ISSUE THREAD

**Issue by hanjunchen** [liaochong/myexcel#316]
多级标题时对二级标题中的某一个标题单独设置样式，注解方式，可以实现吗

**Comment by liaochong** [comment]
抱歉，当前不支持

**Comment by yousetme** [comment]
> 抱歉，当前不支持，如需要，请采用模板方式追加标题

希望能支持下【因为标题颜色需求很常见，现在设置了子title，父title颜色一致了，感觉怪怪的】，看了下源码，大概如下这样子改，不知道合理不。

语法可以类似这样：
@ExcelColumn(order = 3, index = 3, title =  "扩展信息->技能->等级" ,style={"技能:title->color:red","cell->color:green"})

`    private void setEachColumnStyle(String prefix, int fieldIndex, Map<String, String> styleMap) {
        if (styleMap == null || styleMap.isEmpty()) {
            return;
        }
        String stylePrefix = prefix + "&" + fieldIndex; //这里加上行号，取的时候也按这个原则取 prefix + "&" + fieldIndex + "&" + rowIndex
        Map<String, String> parentStyleMap = eachColumnStyle.get(stylePrefix);
        if (parentStyleMap == null || parentStyleMap.isEmpty()) {
            parentStyleMap = new HashMap<>(styleMap);
            eachColumnStyle.put(stylePrefix, parentStyleMap);
        } else {
            parentStyleMap.putAll(styleMap);
        }
        setWidth(fieldIndex, parentStyleMap);
    }
`


![image](https://user-images.githubusercontent.com/7489701/163390035-b26a1192-932d-4c52-bdb7-5cf871ec1859.png)

**Comment by liaochong** [comment]
感谢提议，可以按照你的想法提交一个PR，语法最好是循序渐进，有层次的，比如@ExcelColumn(order = 3, index = 3, title = "扩展信息->技能->等级" ,style={"title&技能->color:red","cell->color:green"})，先表明是标题的样式，再表明是某个具体标题的样式，但建议还是使用模板追加的方式，会简单灵活很多

**Comment by yousetme** [comment]
模板构建确实非常灵活，但这种方式应该是在内存中处理全量数据的吧，如果数据量比较大担心吃内存，主要是使用DefaultStreamExcelBuilder流式处理能力，流式加载数据处理写入。

表头采用模板【灵活】，表格采用动态数据，这种方式感觉也很实用，避免全量渲染数据。

> 感谢提议，可以按照你的想法提交一个PR，语法最好是循序渐进，有层次的，比如@ExcelColumn(order = 3, index = 3, title = "扩展信息->技能->等级" ,style={"title&技能->color:red","cell->color:green"})，先表明是标题的样式，再表明是某个具体标题的样式，但建议还是使用模板追加的方式，会简单灵活很多

很好的提议，实现不复杂的话，我提个PR。

**Comment by liaochong** [comment]
我理解你的意思，你可以看下DefaultStreamExcelBuilder，里面可以设置模板处理器，也就是说，DefaultStreamExcelBuilder也可以追加模板，流式处理，而不是把所有数据都渲染到一个模板上统一处理，这种情况下占用内存也不会很大，在当前问题上，主要是设置标题，标题数据量不会很大，所以标题部分采用模板是可以的

**Comment by yousetme** [comment]
> 感谢提议，可以按照你的想法提交一个PR，语法最好是循序渐进，有层次的，比如@ExcelColumn(order = 3, index = 3, title = "扩展信息->技能->等级" ,style={"title&技能->color:red","cell->color:green"})，先表明是标题的样式，再表明是某个具体标题的样式，但建议还是使用模板追加的方式，会简单灵活很多

HtmlToExcelStreamFactory:226行改一行代码可以支持，但是样式里必须指定标题才生效【"title&技能->color:red"】，如果觉得可以后续升级可以加入支持，或者加入更好的想法【其实这样子我觉得够用了，但是向上不兼容"title->color:red"】，改动比较小我就不提PR了。



td.style = context.styleParser.getTitleStyle("title&" + td.content + "&" + td.col);

**Comment by liaochong** [comment]
嗯嗯，后续版本我考虑下
