### ISSUE TITLE
子类继承父类第一列为子类类名

### ISSUE THREAD

**Issue by objectboy2016** [liaochong/myexcel#321]
![微信截图_20210715184936](https://user-images.githubusercontent.com/16741598/125776427-a3630329-28b4-4907-9284-54c75cbf54da.png)

class a extends b{

}

导出数据:

`list<a>  list=..........`

图中第一列为a类完整类名,  怎么样不显示第一列????

**Comment by objectboy2016** [comment]
> ![微信截图_20210715184936](https://user-images.githubusercontent.com/16741598/125776427-a3630329-28b4-4907-9284-54c75cbf54da.png)
> 
> class a extends b{
> 
> }
> 
> 导出a的数据, 图中第一列为a类完整类名, 怎么样不显示第一列????

**Comment by liaochong** [comment]
能提供下a\b的具体属性吗？

**Comment by liaochong** [comment]
未重现，关闭
