### ISSUE TITLE
提示功能在微软Office上打不开

### ISSUE THREAD

**Issue by libinye** [liaochong/myexcel#324]
**Bug描述**
![image](https://user-images.githubusercontent.com/45119749/131789306-afb7a85d-f725-424a-81b2-e85a6e6dc436.png)
![image](https://user-images.githubusercontent.com/45119749/131789391-b088531d-fe55-4c31-af5f-ed86061fc911.png)

微软Office版本是2013

**Comment by liaochong** [comment]
应该不是提示的问题，而是内容本身有问题导致的
