### ISSUE TITLE
只要设置了rowFilter，exceptionally就不会回调？

### ISSUE THREAD

**Issue by libinye** [liaochong/myexcel#325]
**Bug描述**
![1630576858(1)](https://user-images.githubusercontent.com/45119749/131824542-c8d38249-e20d-4a66-bbd5-3ad130ce3dc7.jpg)
这里只要过滤了行，异常就不会回调，因此会报错。

**Comment by liaochong** [comment]
exceptionally本意是row转化为bean的过程中出现异常，能够让用户感知并决定是否要处理，返回true，只是把异常显示出来，但不会终止读取，返回false，则直接终止读取，如果设置了rowFilter，那么被过滤的行就不会被转化成bean，也就不会调用exceptionally

**Comment by liaochong** [comment]
需要看下具体异常是什么
