### ISSUE TITLE
希望提供一个 预先读取所有数据总行数，不需要对象转换的 越快越好的 功能呢？

### ISSUE THREAD

**Issue by kiwimg** [liaochong/myexcel#334]
使用 SaxExcelReader.of 读取文件时，有时候需要知道总行数，计算处理进度
这样需要预先知道文件总行数，不带空行的总行数

希望读取的性能能很快返回结果，这种是不需要进行对象映射转换，仅仅需要知道总数即可，
怎么快速 怎么实现
谢谢

**Comment by liaochong** [comment]
4.0.0.RC版本已提供，SaxExcelReader.getWorkbookMetaData(new File);
