### ISSUE TITLE
复杂表格渲染部分字段缺失的问题

### ISSUE THREAD

**Issue by onlinecoxx** [liaochong/myexcel#34]
html 上的内容
![html渲染正常](https://user-images.githubusercontent.com/22684056/54967070-45c73680-4fb1-11e9-8b69-b27e3de88985.png)
渲染后excel的内容
![excel渲染缺少部分字段缺失](https://user-images.githubusercontent.com/22684056/54967101-6099ab00-4fb1-11e9-9e9b-d891737069a2.png)
html源码(因为不支持上传html类型改为txt）
[templatePref.txt](https://github.com/liaochong/myexcel/files/3006253/templatePref.txt)

**Comment by liaochong** [comment]
已收到，会尽快解决，感谢🙏

**Comment by liaochong** [comment]
已解决，请升级为2.1.1版本

**Comment by onlinecoxx** [comment]
好的，感谢
