### ISSUE TITLE
导出cellStyle缓存不起作用

### ISSUE THREAD

**Issue by pandening** [liaochong/myexcel#347]
https://github.com/liaochong/myexcel/blob/1589da5a4db61cf8430ba4fa3b49585677fb7018/src/main/java/com/github/liaochong/myexcel/core/AbstractExcelFactory.java#L599

这行代码不起作用，导致每增加一行Excel记录都会创建一次cellStyle，最终导致抛出异常：

`
An exception occurred while processing java.lang.IllegalStateException: The maximum number of Cell Styles was exceeded. You can define up to 64000 style in a .xlsx Workbook 	at org.apache.poi.xssf.model.StylesTable.createCellStyle(StylesTable.java:831) 	at org.apache.poi.xssf.usermodel.XSSFWorkbook.createCellStyle(XSSFWorkbook.java:746) 	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createCellStyle(SXSSFWorkbook.java:884) 	at com.github.liaochong.myexcel.core.AbstractExcelFactory.setCellStyle(AbstractExcelFactory.java:437) 	at com.github.liaochong.myexcel.core.AbstractExcelFactory.createCell(AbstractExcelFactory.java:306) 	at com.github.liaochong.myexcel.core.AbstractExcelFactory.createRow(AbstractExcelFactory.java:198) 	at com.github.liaochong.myexcel.core.HtmlToExcelStreamFactory.appendRow(HtmlToExcelStreamFactory.java:363) 	at com.github.liaochong.myexcel.core.HtmlToExcelStreamFactory.receive(HtmlToExcelStreamFactory.java:182) 	at com.github.liaochong.myexcel.core.HtmlToExcelStreamFactory$Lambda$878/64002610.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745)
`
另一个疑问是，append的记录数量远没有64000行（2w+行），但cellStyle却已经创建了这么多了，这个是否也有问题？

**Comment by liaochong** [comment]
cellStyle是针对每一个单元格来的，和行数不是一对一的关系，能贴一下你导出的代码吗

**Comment by pandening** [comment]
这是来自qq邮箱的自动回复。
您好，感谢您的来信，您的邮件已经投递到该邮箱，但您看到这封回信不代表主人已经看到您的邮件，仅代表您的信件发送成功。
 祝你快乐~

**Comment by liaochong** [comment]
如果确实有这个问题，非常希望您这边能提供一个PR，进行修复🙏

**Comment by pandening** [comment]
> 如果确实有这个问题，非常希望您这边能提供一个PR，进行修复🙏

好的，那我了解了，我们确实遇到了这个问题，不太好贴代码，我可以先提个pr，然后你这边评估一下是否可行

**Comment by pandening** [comment]
> > 如果确实有这个问题，非常希望您这边能提供一个PR，进行修复🙏
> 
> 好的，那我了解了，我们确实遇到了这个问题，不太好贴代码，我可以先提个pr，然后你这边评估一下是否可行

@liaochong  我看在新版里面通过这行代码修复了，这个问题可以关闭了：https://github.com/liaochong/myexcel/blob/1589da5a4db61cf8430ba4fa3b49585677fb7018/src/main/java/com/github/liaochong/myexcel/core/style/BorderStyle.java#L65

**Comment by liaochong** [comment]
好的，感谢使用，欢迎一起构建好用的excel工具
