### ISSUE TITLE
DefaultStreamExcelBuilder 不支持向已存在excel追加多sheet数据

### ISSUE THREAD

**Issue by weiweili666** [liaochong/myexcel#353]
您好，
代码如下：
File file = new File("D://test.xlsx");
DefaultStreamExcelBuilder builder;
Workbook workbook;
builder = DefaultStreamExcelBuilder.of(Student.class).sheet("sheet1").start();
builder.append(data.get(0));
workbook = builder.build();
FileExportUtil.export(workbook , file);
builder = DefaultStreamExcelBuilder.of(Student.class, new FileInputStream(file)).sheet("sheet2").start();
builder.append(data.get(1));
workbook = builder.build();
FileExportUtil.export(workbook , file);

现象：
没有按照预期导出的excel有2个sheet，而是数据都在一个sheet页

请问，是否有办法追加到第2个sheet页

**Comment by liaochong** [comment]
参见文档：https://github.com/liaochong/myexcel/wiki/%E5%A4%9Asheet%E5%AF%BC%E5%87%BA

**Comment by weiweili666** [comment]
我想实现的场景是：查询一批数据，就写入文件，追加写入，不是一把写入文件。不知道这种能否实现多个sheet
Workbook workbook2=DefaultExcelBuilder.of(B.class , workbook1).build(dataList);

**Comment by liaochong** [comment]
有报错吗？对应的版本号是多少？

**Comment by weiweili666** [comment]
没有报错，就是数据只能追加到一个sheet，比如前2条数据在sheet1,这个时候想在追加一条数据到sheet2,就不行了，只会生成一个sheet（shee2）,数据确实都追加了

**Comment by liaochong** [comment]
使用的版本是多少？





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: weiweili ***@***.***&gt;
发送时间: 2022年2月23日 17:36
收件人: liaochong/myexcel ***@***.***&gt;
抄送: 清沐 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [liaochong/myexcel] DefaultStreamExcelBuilder 不支持向已存在excel追加多sheet数据 (Issue #353)

**Comment by liaochong** [comment]
目前还不支持该种类型追加，需要新鲜特性



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: weiweili ***@***.***&gt;
发送时间: 2022年2月23日 17:36
收件人: liaochong/myexcel ***@***.***&gt;
抄送: 清沐 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [liaochong/myexcel] DefaultStreamExcelBuilder 不支持向已存在excel追加多sheet数据 (Issue #353)





 
没有报错，就是数据只能追加到一个sheet，比如前2条数据在sheet1,这个时候想在追加一条数据到sheet2,就不行了，只会生成一个sheet（shee2）,数据确实都追加了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weiweili666** [comment]
3.9.5

**Comment by weiweili666** [comment]
又发下个问题，如果已经存在的excel表头的字段顺序和spring bean 顺序不一致的时候，读取之前已经存在的excel会失败（字段类型不一致），报错日志：
Casued by : com.github.liaochong.myexcel.exception.SaxReadException: Fail to read xlsx file
Casued by : com.github.liaochong.myexcel.exception.Exception.ExcelReadException: Failed to convert content

**Comment by weiweili666** [comment]
DefaultStreamExcelBuilder  start()方法中SaxExcelReader去读取excel时，之前的fieldDisPlayerOrder应该是没有生效

**Comment by liaochong** [comment]
是这样的，为了避免内存占用过高，追加的方式其实是把原来文件中的内容读取出来写入新的文件，这就需要字段和列一一对应。关于追加写入，昨天想了一个方案，还是采用DefaultStreamExcelBuilder.of(class,workbook)方式，但是workbook 产生方式如下：


Workbook wb = WorkbookFactory.create(new File("MyExcel.xls"));

// Use an InputStream, needs more memory
Workbook wb = WorkbookFactory.create(new FileInputStream("MyExcel.xlsx"));

这样就可以实现多次追加写入，也不会出现你说的列不对应导致的问题

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: weiweili ***@***.***&gt;
发送时间: 2022年2月24日 09:50
收件人: liaochong/myexcel ***@***.***&gt;
抄送: 清沐 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [liaochong/myexcel] DefaultStreamExcelBuilder 不支持向已存在excel追加多sheet数据 (Issue #353)





 
又发下个问题，如果已经存在的excel表头的字段顺序和spring bean 顺序不一致的时候，读取之前已经存在的excel会失败（字段类型不一致），报错日志：
 Casued by : com.github.liaochong.myexcel.exception.SaxReadException: Fail to read xlsx file
 Casued by : com.github.liaochong.myexcel.exception.Exception.ExcelReadException: Failed to convert content
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weiweili666** [comment]
您好，尝试了一下，还是有报错。
代码调整如下：
File file = new File("D://test.xlsx");
DefaultStreamExcelBuilder builder;
Workbook workbook;
// 第一次写入，生成一个excel,并写入数据
builder = DefaultStreamExcelBuilder.of(Student.class).sheet("sheet1").start();
builder.append(data.get(0));
workbook = builder.build();
FileExportUtil.export(workbook , file);

// 第二次写入，追加数据
workbook = WorkbookFactory.create(file);
builder = DefaultStreamExcelBuilder.of(Student.class, workbook).sheet("sheet2").start();
builder.append(data.get(1));
workbook = builder.build();
// 这里会报错
FileExportUtil.export(workbook , file);

错误如下：
org.apache.poi.openxml4j.exceptions.OpenXML4JRunti meException: Fail to save: an error occurs while s aving the package : The part /docProps/app.xml fai led to be saved in the stream with marshaller org.

**Comment by liaochong** [comment]
应该是前一次导出文件流没有正常关闭导致的，可以断点看下或者你拿到workbook 后自行写出到某个文件，不通过FileExportUtil



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: weiweili ***@***.***&gt;
发送时间: 2022年2月24日 10:32
收件人: liaochong/myexcel ***@***.***&gt;
抄送: 清沐 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [liaochong/myexcel] DefaultStreamExcelBuilder 不支持向已存在excel追加多sheet数据 (Issue #353)

**Comment by liaochong** [comment]
本地测试，4.0.0版本没有问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: weiweili ***@***.***&gt;
发送时间: 2022年2月24日 10:32
收件人: liaochong/myexcel ***@***.***&gt;
抄送: 清沐 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [liaochong/myexcel] DefaultStreamExcelBuilder 不支持向已存在excel追加多sheet数据 (Issue #353)





 
您好，尝试了一下，还是有报错。
 代码调整如下：
 File file = new File("D://test.xlsx");
 DefaultStreamExcelBuilder builder;
 Workbook workbook;
 // 第一次写入，生成一个excel,并写入数据
 builder = DefaultStreamExcelBuilder.of(Student.class).sheet("sheet1").start();
 builder.append(data.get(0));
 workbook = builder.build();
 FileExportUtil.export(workbook , file);
 
// 第二次写入，追加数据
 workbook = WorkbookFactory.create(file);
 builder = DefaultStreamExcelBuilder.of(Student.class, workbook).sheet("sheet2").start();
 builder.append(data.get(1));
 workbook = builder.build();
 // 这里会报错
 FileExportUtil.export(workbook , file);
 
错误如下：
 org.apache.poi.openxml4j.exceptions.OpenXML4JRunti meException: Fail to save: an error occurs while s aving the package : The part /docProps/app.xml fai led to be saved in the stream with marshaller org.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weiweili666** [comment]
您好，能否把本地测试demo发出来看看，谢谢

**Comment by liaochong** [comment]
除了导出类不同外，其他一致，请问有升级到4.0.0版本尝试吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: weiweili ***@***.***&gt;
发送时间: 2022年2月24日 10:32
收件人: liaochong/myexcel ***@***.***&gt;
抄送: 清沐 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [liaochong/myexcel] DefaultStreamExcelBuilder 不支持向已存在excel追加多sheet数据 (Issue #353)





 
您好，尝试了一下，还是有报错。
 代码调整如下：
 File file = new File("D://test.xlsx");
 DefaultStreamExcelBuilder builder;
 Workbook workbook;
 // 第一次写入，生成一个excel,并写入数据
 builder = DefaultStreamExcelBuilder.of(Student.class).sheet("sheet1").start();
 builder.append(data.get(0));
 workbook = builder.build();
 FileExportUtil.export(workbook , file);
 
// 第二次写入，追加数据
 workbook = WorkbookFactory.create(file);
 builder = DefaultStreamExcelBuilder.of(Student.class, workbook).sheet("sheet2").start();
 builder.append(data.get(1));
 workbook = builder.build();
 // 这里会报错
 FileExportUtil.export(workbook , file);
 
错误如下：
 org.apache.poi.openxml4j.exceptions.OpenXML4JRunti meException: Fail to save: an error occurs while s aving the package : The part /docProps/app.xml fai led to be saved in the stream with marshaller org.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liaochong** [comment]
经测试，3.9.5版本确实会有问题，请升级到4.0.0版本。因4版本使用POI 5，如原项目中存在低版本POI会有冲突，请注意解决



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: weiweili ***@***.***&gt;
发送时间: 2022年2月24日 16:27
收件人: liaochong/myexcel ***@***.***&gt;
抄送: 清沐 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [liaochong/myexcel] DefaultStreamExcelBuilder 不支持向已存在excel追加多sheet数据 (Issue #353)





 
您好，能否把本地测试demo发出来看看，谢谢
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liaochong** [comment]
已明确错误原因，第二次导出请选择不同文件，原文件被占用未释放，所以导致错误



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: weiweili ***@***.***&gt;
发送时间: 2022年2月24日 16:27
收件人: liaochong/myexcel ***@***.***&gt;
抄送: 清沐 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [liaochong/myexcel] DefaultStreamExcelBuilder 不支持向已存在excel追加多sheet数据 (Issue #353)





 
您好，能否把本地测试demo发出来看看，谢谢
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weiweili666** [comment]
导出类能否共享下，我自己写了个导出，发现又生成了个sheet，而不是在原来的基础上追加。

**Comment by liaochong** [comment]
这种方式只能生成新的sheet，要实现你的需求需要改造下：如果存在同名的sheet则追加，否则创建新的sheet&nbsp;
如果比较急的话，可能无法满足你的需要，或者你fork一个分支，自行改造下逻辑

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: weiweili ***@***.***&gt;
发送时间: 2022年2月24日 17:33
收件人: liaochong/myexcel ***@***.***&gt;
抄送: 清沐 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [liaochong/myexcel] DefaultStreamExcelBuilder 不支持向已存在excel追加多sheet数据 (Issue #353)





 
导出类能否共享下，我自己写了个导出，发现又生成了个sheet，而不是在原来的基础上追加。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liaochong** [comment]
要改造也比较简单，HtmlToExcelStreamFactory 163行，先获取workbook 是否存在所需sheet ，如不存在则新增



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: weiweili ***@***.***&gt;
发送时间: 2022年2月24日 17:33
收件人: liaochong/myexcel ***@***.***&gt;
抄送: 清沐 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [liaochong/myexcel] DefaultStreamExcelBuilder 不支持向已存在excel追加多sheet数据 (Issue #353)





 
导出类能否共享下，我自己写了个导出，发现又生成了个sheet，而不是在原来的基础上追加。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liaochong** [comment]
4.0.1版本已发布，支持你的需求
