### ISSUE TITLE
html字符串导出excel失败

### ISSUE THREAD

**Issue by KevinPan1992** [liaochong/myexcel#358]
**Bug描述**
富文本拼接成html之后导出excel失败

**Bug复现**
按如下步骤复现（Steps to reproduce the behavior）:
![image](https://user-images.githubusercontent.com/48461546/159431401-81a31c43-5dfc-4032-b642-71ec24e7756a.png)
![image](https://user-images.githubusercontent.com/48461546/159431493-1a37f385-3c03-4713-94cc-755052ebbad9.png)

**Comment by liaochong** [comment]
版本是多少？另外请在body 中使用table 进行数据导出，这是前提



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: KevinPan1992 ***@***.***&gt;
发送时间: 2022年3月22日 15:43
收件人: liaochong/myexcel ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [liaochong/myexcel] html字符串导出excel失败 (Issue #358)

**Comment by KevinPan1992** [comment]
> 版本是多少？另外请在body 中使用table 进行数据导出，这是前提 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: KevinPan1992 ***@***.***&gt; 发送时间: 2022年3月22日 15:43 收件人: liaochong/myexcel ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [liaochong/myexcel] html字符串导出excel失败 (Issue #358)

![image](https://user-images.githubusercontent.com/48461546/159435238-bbefd332-5fb7-4a7c-9e77-934f175dfd9a.png)

**Comment by liaochong** [comment]
<p>test</p> 修改成 <table><tr><td>test</td></tr></table>试过吗？

**Comment by KevinPan1992** [comment]
> <img alt="image" width="476" src="https://user-images.githubusercontent.com/8674986/159478692-91aad326-23bd-4169-81f5-6548fbbeb8c0.png">

试过的 一样的效果

**Comment by KevinPan1992** [comment]
找到问题了 是前端的问题
追问下 是否支持富文本直接导出excel(可以考虑把P标签等替换成table)

**Comment by liaochong** [comment]
问题解决了？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: KevinPan1992 ***@***.***&gt;
发送时间: 2022年3月24日 09:06
收件人: liaochong/myexcel ***@***.***&gt;
抄送: 清沐 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [liaochong/myexcel] html字符串导出excel失败 (Issue #358)





 
Closed #358.
