### ISSUE TITLE
sheetStrategy(SheetStrategy.ONE_SHEET)无效

### ISSUE THREAD

**Issue by KevinPan1992** [liaochong/myexcel#359]
**Bug描述**
html字符串中有多个table，使用sheetStrategy(SheetStrategy.ONE_SHEET)之后虽然只保留了一个sheet，但是内容没有进行合并
![image](https://user-images.githubusercontent.com/48461546/159674529-0c03e76e-7489-42e6-a0d3-1be2d1f21e81.png)

**版本**
4.0.1

**期望的结果**
多个table可以正常导出到一个sheet中

**Comment by liaochong** [comment]
你指的内容合并是什么意思？目前这种形式，应该有两个table 在一个sheet 中吧



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: KevinPan1992 ***@***.***&gt;
发送时间: 2022年3月23日 18:06
收件人: liaochong/myexcel ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [liaochong/myexcel] sheetStrategy(SheetStrategy.ONE_SHEET)无效 (Issue #359)





 
Bug描述
 html字符串中有多个table，使用sheetStrategy(SheetStrategy.ONE_SHEET)之后虽然只保留了一个sheet，但是内容没有进行合并
 
 
版本
 4.0.1
 
期望的结果
 多个table可以正常导出到一个sheet中

**Comment by KevinPan1992** [comment]
> 你指的内容合并是什么意思？目前这种形式，应该有两个table 在一个sheet 中吧 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: KevinPan1992 ***@***.***&gt; 发送时间: 2022年3月23日 18:06 收件人: liaochong/myexcel ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [liaochong/myexcel] sheetStrategy(SheetStrategy.ONE_SHEET)无效 (Issue #359) Bug描述 html字符串中有多个table，使用sheetStrategy(SheetStrategy.ONE_SHEET)之后虽然只保留了一个sheet，但是内容没有进行合并 版本 4.0.1 期望的结果 多个table可以正常导出到一个sheet中 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

只有第二个table的内容

**Comment by KevinPan1992** [comment]
> 你指的内容合并是什么意思？目前这种形式，应该有两个table 在一个sheet 中吧 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: KevinPan1992 ***@***.***&gt; 发送时间: 2022年3月23日 18:06 收件人: liaochong/myexcel ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [liaochong/myexcel] sheetStrategy(SheetStrategy.ONE_SHEET)无效 (Issue #359) Bug描述 html字符串中有多个table，使用sheetStrategy(SheetStrategy.ONE_SHEET)之后虽然只保留了一个sheet，但是内容没有进行合并 版本 4.0.1 期望的结果 多个table可以正常导出到一个sheet中 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

![image](https://user-images.githubusercontent.com/48461546/159821578-b54da554-2c1c-4096-8cc9-c5bc59ec1c77.png)

**Comment by liaochong** [comment]
4.0.2版本修复，已发布
