### ISSUE TITLE
导入示例代码方法名错误

### ISSUE THREAD

**Issue by JonasHua2013** [liaochong/myexcel#36]
导入示例代码：
public class ArtCrowd {
    // index代表列索引，从0开始
    @ExcelColumn(index = 0)
    private String name;

    @ExcelColumn(index = 1)
    private String age;

    @ExcelColumn(index = 2,dateTimePattern="yyyy-MM-dd")
    private Date birthday;
}

dateTimePattern参照注解方法应该为：dateFormatPattern

**Comment by liaochong** [comment]
出丑了，谢谢
