### ISSUE TITLE
使用模板时进行web导出，如果数据量过大怎么处理？是否支持模板分段导出

### ISSUE THREAD

**Issue by zhenghuanqi** [liaochong/myexcel#360]
**Bug描述**
描述Bug产生的现象（A clear and concise description of what the bug is.）
如上所示，有需求在web界面导出数据，格式有合并列 ，所以需要使用模板导出，但是存在数据量过大的问题，请问有好的解决办法么
**Bug复现**
按如下步骤复现（Steps to reproduce the behavior）:

**期望的结果**
期望的结果是什么（A clear and concise description of what you expected to happen.）
期望模板导出时也可以分段导出。

**Comment by liaochong** [comment]
DefaultStreamExcelBuilder支持分段导出模板，请参考文档



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhenghuanqi ***@***.***&gt;
发送时间: 2022年3月30日 10:27
收件人: liaochong/myexcel ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [liaochong/myexcel] 使用模板时进行web导出，如果数据量过大怎么处理？是否支持模板分段导出 (Issue #360)

**Comment by zhenghuanqi** [comment]
谢谢，我看到DefaultStreamExcelBuilder 可以分段导出，但是我看到是使用java pojo的方式，我想是否可以使用 EnjoyExcelBuilder 方式分段导出。因为我这边导出表格使用的是Enjoy模板，再次感谢您的回复

**Comment by zhenghuanqi** [comment]
谢谢，我看到DefaultStreamExcelBuilder 类里面有引用templateHandler的方法，我试试去。

**Comment by liaochong** [comment]
这个类你随意定一个pojo，比如map，然后在写入数据时全部采用模板追加即可，是支持你所需要的模板引擎的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhenghuanqi ***@***.***&gt;
发送时间: 2022年3月30日 10:40
收件人: liaochong/myexcel ***@***.***&gt;
抄送: 清沐 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [liaochong/myexcel] 使用模板时进行web导出，如果数据量过大怎么处理？是否支持模板分段导出 (Issue #360)
