### ISSUE TITLE
抱歉，想问一下，html模板导出excel ，列中的值字段换行问题

### ISSUE THREAD

**Issue by zhenghuanqi** [liaochong/myexcel#361]
**Bug描述**
描述Bug产生的现象（A clear and concise description of what the bug is.）
在html中使用<br />标签 ，和 style="word-break: break-all;“ 格式， 导出到excel中确实可以换行，但是
第二行开始出会空出一个字符，即第一行和第二行没有对齐
**Bug复现**
按如下步骤复现（Steps to reproduce the behavior）:

**期望的结果**
期望的结果是什么（A clear and concise description of what you expected to happen.）
换行后，各行可以对齐。

**Comment by liaochong** [comment]
是否设置了居中



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhenghuanqi ***@***.***&gt;
发送时间: 2022年3月30日 16:34
收件人: liaochong/myexcel ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [liaochong/myexcel] 抱歉，想问一下，html模板导出excel ，列中的值字段换行问题 (Issue #361)

**Comment by zhenghuanqi** [comment]
你好，麻烦了，还有最后一个问题，我是用 DefaultStreamExcelBuilder 类 分段输出到模板，但是每段都有title行输出到excel中。怎样设置使title只出现excel的第一行。

**Comment by liaochong** [comment]
这个标题是放在模板里面的？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhenghuanqi ***@***.***&gt;
发送时间: 2022年3月30日 18:59
收件人: liaochong/myexcel ***@***.***&gt;
抄送: 清沐 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [liaochong/myexcel] 抱歉，想问一下，html模板导出excel ，列中的值字段换行问题 (Issue #361)

**Comment by zhenghuanqi** [comment]
标题是模板里面的，我想到方法了，我在外面添加了一个变量，在模板里面判断如果不是第一组添加，就不渲染<thead ></thead>,现在还有一个问题就是， excel里面某列自动换行了，但是高度没有自适应，有办法解决么，大神？
