### ISSUE TITLE
Map导出 日期格式化无效

### ISSUE THREAD

**Issue by FeryHuo** [liaochong/myexcel#365]
**Bug描述**
Map导出日期格式化无效
已经添加了
![image](https://user-images.githubusercontent.com/67188859/163336244-19db942f-d6f0-44c8-928c-2ce6e5c80468.png)

**Comment by liaochong** [comment]
Map导出需要自行格式化



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: FeryHuo ***@***.***&gt;
发送时间: 2022年4月14日 15:32
收件人: liaochong/myexcel ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [liaochong/myexcel] Map导出 日期格式化无效 (Issue #365)





 
Bug描述
 Map导出日期格式化无效
 已经添加了

**Comment by FeryHuo** [comment]
![image](https://user-images.githubusercontent.com/67188859/163337475-b0ea79db-e5f0-4d41-9da3-32c2cd10c9a7.png)
目前来看图片字段是正常的，日期是否需要自行格式化转为字符串？

**Comment by liaochong** [comment]
需要的，因为map导出无法识别你需要格式化成什么样，不需要用Pair

**Comment by FeryHuo** [comment]
好的谢谢

**Comment by liaochong** [comment]
下个版本我改下，针对时间类，给个默认导出格式
