### ISSUE TITLE
超过10万条数据后显示错误

### ISSUE THREAD

**Issue by endlesshh** [liaochong/myexcel#372]
**Bug描述**
当导出的数据超过10万条后，Excel中的数据10万条后的就错乱了

**Comment by liaochong** [comment]
哪个版本？导出方式？怎么错乱？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: endless ***@***.***&gt;
发送时间: 2022年7月13日 18:05
收件人: liaochong/myexcel ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [liaochong/myexcel] 超过10万条数据后显示错误 (Issue #372)

**Comment by liaochong** [comment]
无后续反馈，关闭
