### ISSUE TITLE
MyExcel4.2.0 xlsx读取时间格式不准确

### ISSUE THREAD

**Issue by zqkwcyx** [liaochong/myexcel#377]
**Bug描述**
MyExcel4.2.0 xlsx读取时间格式不准确
2022/2/28 17:00:00    读取到的是44123.21321

**Comment by liaochong** [comment]
接收数据的格式是什么？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zqkwcyx ***@***.***&gt;
发送时间: 2022年8月12日 16:58
收件人: liaochong/myexcel ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [liaochong/myexcel] MyExcel4.2.0 xlsx读取时间格式不准确 (Issue #377)

**Comment by zqkwcyx** [comment]
excel里的是2022/2/28 17:00:00    读出来是44123.21321，   只有xlsx会，xls不会

**Comment by zqkwcyx** [comment]
excel的单元格里是日期类型吧

**Comment by liaochong** [comment]
这是excel存储日期的一种格式，不是bug ，如果用String 接收可能会有这样的问题，你可以改成Date来接收



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zqkwcyx ***@***.***&gt;
发送时间: 2022年8月12日 17:01
收件人: liaochong/myexcel ***@***.***&gt;
抄送: 清沐 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [liaochong/myexcel] MyExcel4.2.0 xlsx读取时间格式不准确 (Issue #377)





 
excel里的是2022/2/28 17:00:00    读出来是44123.21321，   只有xlsx会，xls不会

**Comment by liaochong** [comment]
Excel显示和存储的格式没有必然关系



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zqkwcyx ***@***.***&gt;
发送时间: 2022年8月12日 17:03
收件人: liaochong/myexcel ***@***.***&gt;
抄送: 清沐 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [liaochong/myexcel] MyExcel4.2.0 xlsx读取时间格式不准确 (Issue #377)





 
excel的单元格里是日期类型吧

**Comment by zqkwcyx** [comment]
List<Map> dataList = SaxExcelReader.of(Map.class).sheet(0).read(inputStream); 这转出来直接就是44123.21321这种数据格式了

**Comment by liaochong** [comment]
这种读出来就是String格式的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zqkwcyx ***@***.***&gt;
发送时间: 2022年8月12日 17:05
收件人: liaochong/myexcel ***@***.***&gt;
抄送: 清沐 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [liaochong/myexcel] MyExcel4.2.0 xlsx读取时间格式不准确 (Issue #377)





 
List dataList = SaxExcelReader.of(Map.class).sheet(0).read(inputStream); 这转出来直接就是44123.21321这种数据格式了

**Comment by zqkwcyx** [comment]
我只能用这种方式接，因为excel数据量大，且无法确认属性（存在各种各样的sheet），有没有其他办法可解决接的时间不准问题呢

**Comment by liaochong** [comment]
这个只能自行转换了，可以参考源码中DateReadConverter



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zqkwcyx ***@***.***&gt;
发送时间: 2022年8月12日 17:15
收件人: liaochong/myexcel ***@***.***&gt;
抄送: 清沐 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [liaochong/myexcel] MyExcel4.2.0 xlsx读取时间格式不准确 (Issue #377)





 
我只能用这种方式接，因为excel数据量大，且无法确认属性（存在各种各样的sheet），有没有其他办法可解决接的时间不准问题呢

**Comment by zqkwcyx** [comment]
好的，谢谢啦
