### ISSUE TITLE
WorkbookType设置成xls时，不能添加自定义背景色

### ISSUE THREAD

**Issue by wuliugang** [liaochong/myexcel#38]
WorkbookType设置成xls时，不能添加自定义背景色

**Comment by wuliugang** [comment]
ExcelBuilder excelBuilder = new FreemarkerExcelBuilder();
excelBuilder.workbookType(WorkbookType.XLS);

**Comment by liaochong** [comment]
您好，我使用FreemarkerExcelBuilder构建时，背景色显示正常，如果可能，请提供下对应的html文件，或者加入QQ群：135520370，尽快解决问题，谢谢！

**Comment by liaochong** [comment]
已复现，2.1.2版本修复，2019-03-29发布上传，2019-03-30可下载

**Comment by liaochong** [comment]
2.1.2已发布，预计2019/03/31可下载
