### ISSUE TITLE
Beetl模板测试方法生成的xls未导出titles和data

### ISSUE THREAD

**Issue by ggww** [liaochong/myexcel#387]
**Bug描述**
使用4.3.0.RC3版本的BeetlExcelBuilderTest测试方法，验证导出数据文件有问题

**Bug复现**
1、执行BeetlExcelBuilderTest测试方法
2、查看导出文件beetl_file_build.xlsx数据
3、显示内容如下：
![image](https://user-images.githubusercontent.com/16686495/226797526-bde0d782-8282-49a0-b346-99700dc034c5.png)

**期望的结果**
希望能正确导出数据

**Comment by liaochong** [comment]
模板文件出了点问题，部分<%出现了分离，可以修正下
