### ISSUE TITLE
合并单元格如何处理

### ISSUE THREAD

**Issue by yzy-1995** [liaochong/myexcel#391]
|项目编号|                                       项目总额                                                |
               |             劳务合同费用             |             机械租赁合同费用            | 
               
              这种合并的单元格如何去处理呢？

**Comment by liaochong** [comment]
不太明白，是导入还是导出？单元格具体怎么合并？能否提供一张图？

**Comment by yzy-1995** [comment]
导入，可以提供图。
![image](https://user-images.githubusercontent.com/24284910/233878281-8fdb831d-2b59-47a2-a656-079f3cdbb2f2.png)

**Comment by liaochong** [comment]
你可以按照列索引导入，ExcelColumn(index=xx)，然后使用rowFilter(row->row.getRowNum()>1)，也可以按照标题导入，如项目付款总额->材料付款

**Comment by yzy-1995** [comment]
谢谢，我用index成功了。
