### ISSUE TITLE
请问myexcel能读取单元格内文字字体、颜色等样式吗？

### ISSUE THREAD

**Issue by mostcool** [liaochong/myexcel#394]
**Bug描述**
请问myexcel能读取单元格内文字字体、颜色等样式吗？

**Bug复现**
请问myexcel能读取单元格内文字字体、颜色等样式吗？

**期望的结果**
请问myexcel能读取单元格内文字字体、颜色等样式吗？

**Comment by liaochong** [comment]
抱歉，暂时不能
