### ISSUE TITLE
Freemarker导出的时候excel样式没生效

### ISSUE THREAD

**Issue by wpzym1125** [liaochong/myexcel#407]
您好，      
  ExcelBuilder excelBuilder = new FreemarkerExcelBuilder();
        Workbook workbook = excelBuilder.classpathTemplate("/templates/importUserExcelTemplate.ftl").workbookType(WorkbookType.XLSX).applyDefaultStyle()
                .build(dataMap);
![1702281315540](https://github.com/liaochong/myexcel/assets/3870054/770d67ab-d6fb-477c-8bd9-e42b279575d4)
导出的excel里面没有背景色

是我参数设置的不对么？麻烦看下，谢谢

**Comment by liaochong** [comment]
使用默认样式applyDefaultStyle？如果需要自定义样式，删除，另外，也不需要设定XLSX，默认就是

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 王培 ***@***.***&gt;
发送时间: 2023年12月11日 15:56
收件人: liaochong/myexcel ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [liaochong/myexcel] Freemarker导出的时候excel样式没生效 (Issue #407)





 
您好，
 ExcelBuilder excelBuilder = new FreemarkerExcelBuilder();
 Workbook workbook = excelBuilder.classpathTemplate("/templates/importUserExcelTemplate.ftl").workbookType(WorkbookType.XLSX).applyDefaultStyle()
 .build(dataMap);
 1702281315540.png (view on web)
 导出的excel里面没有背景色
 
是我参数设置的不对么？麻烦看下，谢谢

**Comment by liaochong** [comment]
4.4.0版本测试正常



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 王培 ***@***.***&gt;
发送时间: 2023年12月11日 15:56
收件人: liaochong/myexcel ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [liaochong/myexcel] Freemarker导出的时候excel样式没生效 (Issue #407)





 
您好，
 ExcelBuilder excelBuilder = new FreemarkerExcelBuilder();
 Workbook workbook = excelBuilder.classpathTemplate("/templates/importUserExcelTemplate.ftl").workbookType(WorkbookType.XLSX).applyDefaultStyle()
 .build(dataMap);
 1702281315540.png (view on web)
 导出的excel里面没有背景色
 
是我参数设置的不对么？麻烦看下，谢谢

**Comment by wpzym1125** [comment]
我删除了applyDefaultStyle  但是我设置了1个背景色，文字就没有垂直居中了，这个是什么样式设置的？
![1702282183392](https://github.com/liaochong/myexcel/assets/3870054/c7af1f77-0935-4ec5-a49f-1f4b90cf0bf3)

**Comment by wpzym1125** [comment]
<table style=" border: 1px solid black;border-collapse: collapse;">

**Comment by wpzym1125** [comment]
![1702283972392](https://github.com/liaochong/myexcel/assets/3870054/b67569f6-f491-4fb4-8b33-719365c6dc1d)

**Comment by liaochong** [comment]
请参考
https://github.com/liaochong/myexcel/wiki/Style-support

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 王培 ***@***.***&gt;
发送时间: 2023年12月11日 16:39
收件人: liaochong/myexcel ***@***.***&gt;
抄送: 清沐 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [liaochong/myexcel] Freemarker导出的时候excel样式没生效 (Issue #407)





 
1702283972392.png (view on web)

**Comment by wpzym1125** [comment]
可以了，谢谢
