### ISSUE TITLE
换行样式未生效

### ISSUE THREAD

**Issue by wpzym1125** [liaochong/myexcel#408]
![1702352415714](https://github.com/liaochong/myexcel/assets/3870054/7c066d22-2dab-4b15-9e0b-2d3e17bf862e)
麻烦看下，为什么没有自动换行？

**Comment by liaochong** [comment]
行高不够



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 王培 ***@***.***&gt;
发送时间: 2023年12月12日 11:41
收件人: liaochong/myexcel ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [liaochong/myexcel] 换行样式未生效 (Issue #408)





 
1702352415714.png (view on web)
 麻烦看下，为什么没有自动换行？

**Comment by wpzym1125** [comment]
行高怎么设置？能自适应吗

**Comment by liaochong** [comment]
不能自适应，你在tr上设置样式，height:50px



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 王培 ***@***.***&gt;
发送时间: 2023年12月12日 13:34
收件人: liaochong/myexcel ***@***.***&gt;
抄送: 清沐 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [liaochong/myexcel] 换行样式未生效 (Issue #408)





 
行高怎么设置？能自适应吗

**Comment by wpzym1125** [comment]
那有几百个字符的时候，我要自己去计算高度么？问题是到底换行后是几行我也不知道呀

**Comment by liaochong** [comment]
已修复该问题，请使用4.4.1版本
