### ISSUE TITLE
导入Excel时，字符 51356317.21 转化成科学计数法

### ISSUE THREAD

**Issue by feiketongxue** [liaochong/myexcel#425]
**Bug描述**
<img width="330" alt="image" src="https://github.com/user-attachments/assets/72244a80-2890-4a99-b7b8-14f098b7f4ed">

**Bug复现**
按如下步骤复现（Steps to reproduce the behavior）:
我目前在维护一个老项目，在项目中使用了 myExcel
因为是在金融行业，很多版本无法升级，所以希望您可以帮助到我
版本为 
```xml
<dependency>
    <groupId>com.github.liaochong</groupId>
    <artifactId>myexcel</artifactId>
    <version>3.9.5</version>
</dependency>
```

```java 
    @Test
    void testReadXlsxWithTitle() throws Exception {
        URL htmlToExcelEampleURL = this.getClass().getResource("/20240624.xlsx");
        Path path = Paths.get(htmlToExcelEampleURL.toURI());

        SaxExcelReader.of(TzzcmxbDTO.class)
                .rowFilter(row -> row.getRowNum() > 0)
                .readThen(path.toFile(), d -> {
                    System.out.println(d.toString());
                });
    }

导入之后为 账面余额，账面价值使用科学计数法：
TzzcmxbDTO(tzcb=34184.33, zmye=34184.33, zmjz=34184.33, fe=null)
TzzcmxbDTO(tzcb=51330606.96, zmye=5.135631721E7, zmjz=5.135631721E7, fe=null)
TzzcmxbDTO(tzcb=30715956.15, zmye=3.086502459E7, zmjz=3.086502459E7, fe=null)
TzzcmxbDTO(tzcb=30000000000.11, zmye=5924910.12, zmjz=5924910, fe=null)

```

再次希望您可以帮助我一下，
在此 对您表示诚挚的感谢！

**Comment by feiketongxue** [comment]
```java 
// TzzcmxbDTO 类为
import com.github.liaochong.myexcel.core.WorkbookType;
import com.github.liaochong.myexcel.core.annotation.ExcelColumn;
import com.github.liaochong.myexcel.core.annotation.ExcelModel;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;

@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@ExcelModel(workbookType = WorkbookType.SXLSX)
public class TzzcmxbDTO {

    /**
     * 投资成本
     */
    @ExcelColumn(title = "*投资成本", convertToString = true, style={"title->color:#FD0000","title->background-color:#FABF8F","title->font-size:11px","title->font-weight:normal"})
    private String tzcb;

    /**
     * 账面余额
     */
    @ExcelColumn(title = "*账面余额", convertToString = true, style={"title->color:#FD0000","title->background-color:#FABF8F","title->font-size:11px","title->font-weight:normal"})
    private String zmye;

    /**
     * 账面价值
     */
    @ExcelColumn(title = "*账面价值", convertToString = true, style={"title->color:#FD0000","title->background-color:#FABF8F","title->font-size:11px","title->font-weight:normal"})
    private String zmjz;

    /**
     * 份额
     */
    @ExcelColumn(title = "份额", convertToString = true, style={"title->color:#FD0000","title->background-color:#FABF8F","title->font-size:11px","title->font-weight:normal"})
    private String fe;
    
}

```

**Comment by liaochong** [comment]
用Bigdecimal来接收



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: feiketongxue ***@***.***&gt;
发送时间: 2024年7月21日 13:06
收件人: liaochong/myexcel ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [liaochong/myexcel] 导入Excel时，字符 51356317.21 转化成科学计数法 (Issue #425)





 // TzzcmxbDTO 类为 import com.github.liaochong.myexcel.core.WorkbookType; import com.github.liaochong.myexcel.core.annotation.ExcelColumn; import com.github.liaochong.myexcel.core.annotation.ExcelModel; import lombok.Data; import lombok.EqualsAndHashCode; import lombok.experimental.Accessors; @Data @EqualsAndHashCode(callSuper = false) @Accessors(chain = true) @ExcelModel(workbookType = WorkbookType.SXLSX) public class TzzcmxbDTO {     /**      * 投资成本      */     @ExcelColumn(title = "*投资成本", convertToString = true, style={"title-&gt;color:#FD0000","title-&gt;background-color:#FABF8F","title-&gt;font-size:11px","title-&gt;font-weight:normal"})     private String tzcb;     /**      * 账面余额      */     @ExcelColumn(title = "*账面余额", convertToString = true, style={"title-&gt;color:#FD0000","title-&gt;background-color:#FABF8F","title-&gt;font-size:11px","title-&gt;font-weight:normal"})     private String zmye;     /**      * 账面价值      */     @ExcelColumn(title = "*账面价值", convertToString = true, style={"title-&gt;color:#FD0000","title-&gt;background-color:#FABF8F","title-&gt;font-size:11px","title-&gt;font-weight:normal"})     private String zmjz;     /**      * 份额      */     @ExcelColumn(title = "份额", convertToString = true, style={"title-&gt;color:#FD0000","title-&gt;background-color:#FABF8F","title-&gt;font-size:11px","title-&gt;font-weight:normal"})     private String fe;      }

**Comment by feiketongxue** [comment]
确实可以了 谢谢您，实在没想到您可以回复我的邮件

十分感谢










在 2024-07-22 14:59:50，"清沐" ***@***.***> 写道：

用Bigdecimal来接收



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: feiketongxue ***@***.***&gt;
发送时间: 2024年7月21日 13:06
收件人: liaochong/myexcel ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [liaochong/myexcel] 导入Excel时，字符 51356317.21 转化成科学计数法 (Issue #425)





// TzzcmxbDTO 类为 import com.github.liaochong.myexcel.core.WorkbookType; import com.github.liaochong.myexcel.core.annotation.ExcelColumn; import com.github.liaochong.myexcel.core.annotation.ExcelModel; import lombok.Data; import lombok.EqualsAndHashCode; import lombok.experimental.Accessors; @Data @EqualsAndHashCode(callSuper = false) @Accessors(chain = true) @ExcelModel(workbookType = WorkbookType.SXLSX) public class TzzcmxbDTO { /** * 投资成本 */ @ExcelColumn(title = "*投资成本", convertToString = true, style={"title-&gt;color:#FD0000","title-&gt;background-color:#FABF8F","title-&gt;font-size:11px","title-&gt;font-weight:normal"}) private String tzcb; /** * 账面余额 */ @ExcelColumn(title = "*账面余额", convertToString = true, style={"title-&gt;color:#FD0000","title-&gt;background-color:#FABF8F","title-&gt;font-size:11px","title-&gt;font-weight:normal"}) private String zmye; /** * 账面价值 */ @ExcelColumn(title = "*账面价值", convertToString = true, style={"title-&gt;color:#FD0000","title-&gt;background-color:#FABF8F","title-&gt;font-size:11px","title-&gt;font-weight:normal"}) private String zmjz; /** * 份额 */ @ExcelColumn(title = "份额", convertToString = true, style={"title-&gt;color:#FD0000","title-&gt;background-color:#FABF8F","title-&gt;font-size:11px","title-&gt;font-weight:normal"}) private String fe; }
