### ISSUE TITLE
对合并的单元格设置了width属性只对第一个单元格生效

### ISSUE THREAD

**Issue by lcgyl** [liaochong/myexcel#428]
对合并的单元格设置了width属性，但是导出来只对第一个单元格生效了，这个有啥好办法可以解决不？
<img width="530" alt="f7120b95ef540491e41022297b34f002" src="https://github.com/user-attachments/assets/d3cc809a-e930-429d-a27e-ed833f4a8cbf">

**Comment by nltheme** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by liaochong** [comment]
4.5.6版本修复，width将会对合并的所有单元格生效
