### ISSUE TITLE
是否可以通过ExcelColumn控制 字段是否导出呢?

### ISSUE THREAD

**Issue by Rekoe** [liaochong/myexcel#56]
问题1 RT
问题2 pojo中的private static final long serialVersionUID = 4883836472385315194L;
发现也被导出到表格中了?
请问这两个问题可以处理下么?

**Comment by Rekoe** [comment]
另外boolean类型可以可以true/false 转 1/0 么

**Comment by liaochong** [comment]
问题1:如某些字段不需要导出，请使用注解@ExcludeColumn，该字段将不被导出，或者在@ExcelTable中设置includeAllField=false

问题2:如问题1

问题3:boolean目前还需要自行处理完成后转化为1/0，2.3.0版本将会提供转换实现

**Comment by Rekoe** [comment]
谢谢 持续关注 等待2.3.0
