### ISSUE TITLE
请问原来的的老版本还能使用吗？

### ISSUE THREAD

**Issue by wlmousecat** [liaochong/myexcel#60]
目前公司的环境还是在JDK7，但是发现html2excel不但已经改名，所有代码也都变成了jdk8，甚至我之前能够在JDK7环境下使用的版本，现在也同样提示版本错误。
请问使用遗留老版本的系统，现在还能使用老版本吗？

**Comment by liaochong** [comment]
非常抱歉，无论是html2excel还是myexcel一直都是基于jdk8的，而且上传到maven中央仓库的包一经上传是不允许被修改的，也就是说不太可能存在同一版本在不同时候提示版本错误的问题。

对于您所遇到的问题，可以给出的解决方案有：
1.您可以fork本项目，将jdk8的语法修改成兼容jdk6的语法，主要是对列表的操作；
2.可以使用阿里巴巴easyexcel或者其他类似的工具；

再次对您遇到的问题感到抱歉！
