### ISSUE TITLE
Long类型数据导入导出问题

### ISSUE THREAD

**Issue by jeesun** [liaochong/myexcel#74]
Long类型的数据，导出后变成了科学计数法。再导入，导入失败，读不到数据。

**Comment by liaochong** [comment]
1.导出后变成科学计数法是因为excel本身的机制，如果不想变成科学计数法，请将该属性类型改为String；
2.能否提供下导入失败的文件或者异常截图

**Comment by jeesun** [comment]
啥异常都没报。这是最气的。

**Comment by liaochong** [comment]
你指的失败是什么意思呢？

**Comment by jeesun** [comment]
我导出的xlsx，里面有多行数据。导入，失败，读不到一行数据。我这是直接导出再导入，中间没做任何操作。

**Comment by liaochong** [comment]
导入是需要相关配置的，没有出现异常那就说明是没有配置
![image](https://user-images.githubusercontent.com/8674986/59013901-ce920680-886d-11e9-890d-fc29783ad758.png)
index用来指明需要导入的列

**Comment by liaochong** [comment]
导出order，导入index，这是个设计问题，在后续版本会进行兼容

**Comment by jeesun** [comment]
原来如此。期待后续的兼容。但还有一个问题，long类型数据166722679628365824导出后，再导入，变成了166720000000000000。

**Comment by liaochong** [comment]
excel中显示的值是多少？

**Comment by jeesun** [comment]
1.6672E+17

**Comment by jeesun** [comment]
注解能不能加一个类型强转的属性。允许long被强转为String。因为会有表id设计的是long这种情况。总不可能每次都让改表。

**Comment by liaochong** [comment]
1.原值被excel处理成了1.6672E+17，所以导入的时候后面全是0是没有问题的;
2.导出是基于导出类，而不是表，也就是说和表结构是无关的，但我觉得这个提议是不错的，新增一个强制输出为String的注解可能会在某些情况下带来便利；

**Comment by liaochong** [comment]
会考虑加入这个特性

**Comment by jeesun** [comment]
好的。期待。之前用的阿里的easyexcel，不支持这个特性，而且更新无望，所以我弃坑了。

**Comment by liaochong** [comment]
最多6月中旬就会发布带有这个特性的版本-2.5.0，感谢提议，如果还有其他建议，还请尽情提出

**Comment by jeesun** [comment]
嗯嗯，期待新版本 (*^▽^*)

**Comment by liaochong** [comment]
2.5.0版本已发布，您提交的convertToString已可用

**Comment by jeesun** [comment]
好的\(^o^)/~
