### ISSUE TITLE
导入时如何设置终止条件

### ISSUE THREAD

**Issue by an9xyz** [liaochong/myexcel#78]
能否给出一些示例？

**Comment by liaochong** [comment]
目前读取没有终止条件设定，会全量读取，只存在行过滤以及Bean过滤，如果可能，请您明确下需求，我这边会作为一个增强点在最近的一个版本中加入

**Comment by an9xyz** [comment]
比如说，每行数据都要进行校验，这个错误信息一直累计，导入的错误数据超过50个时就中止导入任务
以上需求可能就是个例，如果能设定失败的次数来中止导入就好了
目前实现的方式是向上抛继承RuntimeException来中止导入

**Comment by liaochong** [comment]
嗯嗯，这是一个合理且常用的功能，可以考虑提供

**Comment by liaochong** [comment]
2.6.2版本提供 readThen(Function<T,Boolean> function)接口，function返回false表示终止读取

**Comment by kiwimg** [comment]
这个应该放在文档里面 说明一下
