### ISSUE TITLE
如何设定只从第几行开始读取数据？

### ISSUE THREAD

**Issue by yaakua** [liaochong/myexcel#80]
现有的rowFilter写法不是很明白。而且根据文档当中的代码`.sheet(0).rowFilter(row -> row.getRowNum() > 0)` 没明白是什么意思。是否可以直接提供一个简单的可以设置的参数？

**Comment by yaakua** [comment]
直接copy文档当中的.sheet(0).rowFilter(row -> row.getRowNum() > 0) 代码会提示row.getRowNum方法不存在

**Comment by liaochong** [comment]
rowFilter就是为了过滤行的，能提供下完整代码截图吗

**Comment by liaochong** [comment]
另外请提供下poi的版本号

**Comment by yaakua** [comment]
我这边需要做一个通用的导入功能，每个导入的文件都是根据业务场景动态去设置不同的过滤条数。

**Comment by yaakua** [comment]
![image](https://user-images.githubusercontent.com/1543846/59493637-e137bb80-8ebd-11e9-8c67-9c8b0fc56d25.png)
忘记上传图片了。 图片当中我会根据前台用户传入的一个beanName动态去调用每个bean给我的ofClass对象。同时这里需要动态取设置过滤的行数。

**Comment by liaochong** [comment]
先解决第一个问题吧，row.会提示有什么方法？

**Comment by yaakua** [comment]
row就是一个普通的java类，Object父类里面有的方法都有，其余的都没有。我估计是因为没有加上T泛型导致的

**Comment by yaakua** [comment]
![image](https://user-images.githubusercontent.com/1543846/59494564-fca3c600-8ebf-11e9-9431-0b7831b99f83.png)

**Comment by liaochong** [comment]
![image](https://user-images.githubusercontent.com/8674986/59494634-29f07400-8ec0-11e9-908f-b3d36f61e2b3.png)

**Comment by liaochong** [comment]
Class clazz= 改为 Class<?> clazz

**Comment by yaakua** [comment]
> Class clazz= 改为 Class<?> clazz

加上这个代码不报错，但是想问一下我的原始问题如何解决？怎么设定只从第几行开始读取数据

**Comment by liaochong** [comment]
row.getRowNum>0就是从第一行读取，大于1就是从第二行开始读取，依次类推

**Comment by yaakua** [comment]
非常感谢，问题解决！
