### ISSUE TITLE
导出文件时对应的类注解是否可以加上样式支持？

### ISSUE THREAD

**Issue by yaakua** [liaochong/myexcel#83]
现在需要导出Excel文件，用的是默认的实现方式，可否在注解上加上样式支持？比如设置背景色或者字体颜色什么的。

当然最好是能动态根据值来设置样式，比如我有一个返回数据集合，希望能做到根据返回集合的值判断该列是否需要添加不一样的样式。

**Comment by liaochong** [comment]
感谢提议，会考虑加上

**Comment by liaochong** [comment]
2.7.3版本List< Bean >已支持样式自定义
