### ISSUE TITLE
应该对单数日期进行自动补零;

### ISSUE THREAD

**Issue by cielswift** [liaochong/myexcel#85]
**Bug复现**
如果excel 中是这样的"2009/8/27",会报错
Unparseable date: "2009/8/27";

**期望的结果**
可不可以对其进行自动补零2009/08/27;

**Comment by liaochong** [comment]
@ExcelColumn(index = 7, dateFormatPattern = "yyyy/MM/dd") 会自动补0

**Comment by cielswift** [comment]
Unparseable date: "2009/8/27"; 会报这个错,

**Comment by liaochong** [comment]
加上dateFormatPattern = "yyyy/M/dd"还是报错？

**Comment by cielswift** [comment]
源码中也没有发现补0的操作;

    @Override
    public Date doConvert(String v, Field field) {
        if (isNumber(v)) {
            final long time = Long.parseLong(v);
            return new Date(time);
        }
        String dateFormatPattern = getDateFormatPattern(field);
        SimpleDateFormat sdf = simpleDateFormatWeakCache.get(dateFormatPattern);
        if (Objects.isNull(sdf)) {
            sdf = new SimpleDateFormat(dateFormatPattern);
            simpleDateFormatWeakCache.cache(dateFormatPattern, sdf);
        }
        try {
            return sdf.parse(v);
        } catch (ParseException e) {
            throw new RuntimeException(e);
        }
    }

**Comment by cielswift** [comment]
是的:

**Comment by liaochong** [comment]
![image](https://user-images.githubusercontent.com/8674986/59671632-95a04d00-91f0-11e9-9fba-7fbac5d00f64.png)
![image](https://user-images.githubusercontent.com/8674986/59671663-9e911e80-91f0-11e9-8961-3d9282498459.png)
我这边测试了可以的哈，补充0是parse的操作，麻烦贴一下字段设置吧

**Comment by cielswift** [comment]
![1PNG](https://user-images.githubusercontent.com/42295829/59672022-4c043200-91f1-11e9-9ec6-de7b9d923c80.PNG)
public class ArtCrowd {
	
	    // index代表列索引，从0开始
	    @ExcelColumn(index = 0)
	    private Integer id;

	    @ExcelColumn(index = 1)
	    private String name;

	    @ExcelColumn(index = 5,dateFormatPattern="yyyy-MM-dd")
	    private Date date;

		@Override
		public String toString() {
			return "ArtCrowd [id=" + id + ", name=" + name + ", date=" + date + "]";
		}

}

**Comment by liaochong** [comment]
yyyy-MM-dd改成yyyy/MM/dd

**Comment by cielswift** [comment]
你写的是1个 M ?

**Comment by liaochong** [comment]
都可以，主要是-替换为/

**Comment by cielswift** [comment]
...没注意,尴尬,从教学文档复制过来的;
