### ISSUE TITLE
支持Map或Json类型导入导出

### ISSUE THREAD

**Issue by Zeroman** [liaochong/myexcel#94]
实际使用中，map类型的数据很多，map的好处是动态属性。更加灵活，如果能支持导出或是导出就好了。
我阅读了源代码，本来计划用动态类实现，发现搞不定，因为目前的实现和Field类关联较多。改动可能较多。
建议build支持List<Map<String, Object>> dataMapList,这种数据类型的导入。

**Comment by liaochong** [comment]
Map里面对应的key/value分别是什么呢？还请举个例子

**Comment by Zeroman** [comment]
List<Map<String, String>> dataMapList = new ArrayList<>();
            Map<String, String> v1 = new HashMap<>();
            v1.put("a", "数据a1");
            v1.put("b", "数据b1");
            Map<String, String> v2 = new HashMap<>();
            v2.put("a", "数据a2");
            v2.put("b", "数据b2");
            dataMapList.add(v1);
            dataMapList.add(v2);
key对应类的属性名字。抽象看，map就是一个动态类

**Comment by Zeroman** [comment]
使用示例：
`        Map<String, String> headerMap = new HashMap<>();
        headerMap.put("a", "测试A");
        headerMap.put("b", "测试B");
        List<Map<String, String>> dataMapList = new ArrayList<>();
        Map<String, String> v1 = new HashMap<>();
        v1.put("a", "数据a1");
        v1.put("b", "数据b1");
        Map<String, String> v2 = new HashMap<>();
        v2.put("a", "数据a2");
        v2.put("b", "数据b2");
        dataMapList.add(v1);
        dataMapList.add(v2);

        List<String> titles = new ArrayList(headerMap.values());
        List<String> orders = new ArrayList(headerMap.keySet());
        Workbook workbook = DefaultExcelBuilder.getInstance()
                .sheetName("sheet1")
                .titles(titles)
                .fieldDisplayOrder(orders)
                .build(dataMapList);
        FileExportUtil.export(workbook, new File("/tmp/zz.xlsx"));`

**Comment by Zeroman** [comment]
使用示例：
``` java
        Map<String, String> headerMap = new HashMap<>();
        headerMap.put("a", "测试A");
        headerMap.put("b", "测试B");
        List<Map<String, String>> dataMapList = new ArrayList<>();
        Map<String, String> v1 = new HashMap<>();
        v1.put("a", "数据a1");
        v1.put("b", "数据b1");
        Map<String, String> v2 = new HashMap<>();
        v2.put("a", "数据a2");
        v2.put("b", "数据b2");
        dataMapList.add(v1);
        dataMapList.add(v2);

        List<String> titles = new ArrayList(headerMap.values());
        List<String> orders = new ArrayList(headerMap.keySet());
        Workbook workbook = DefaultExcelBuilder.getInstance()
                .sheetName("sheet1")
                .titles(titles)
                .fieldDisplayOrder(orders)
                .build(dataMapList);
        FileExportUtil.export(workbook, new File("/tmp/zz.xlsx"));
```

**Comment by liaochong** [comment]
需求了解了，感谢🙏

**Comment by liaochong** [comment]
2.7.1提供，预计2019/06/08可用

**Comment by Zeroman** [comment]
> 用

感谢!
