### ISSUE TITLE
支持枚举值吗？用convertToString = true没效果

### ISSUE THREAD

**Issue by qinkangdeid** [liaochong/myexcel#95]
**Bug描述**
描述Bug产生的现象（A clear and concise description of what the bug is.）
我导出实体里又一个字段是一个枚举类，例如：
```java
  @ExcelColumn(order = 6, title = "中奖月份", convertToString = true)
    private PrizeTypeEnum prizeType;
```

```java
public enum PrizeTypeEnum {
    /**
     * COUPON 优惠券劵码
     */
    COUPON(1,  "CSV劵码"),
    /**
     * 实体奖品
     */
    ENTITY(2,  "实体奖品"),
    /**
     * 积分
     */
    INTEGRAL(3,  "积分");

    int id;
    String name;
```
导出来的是
`PrizeTypeEnum.ENTITY(id=2,  name=实体奖品)`

**Bug复现**
按如下步骤复现（Steps to reproduce the behavior）:

如上所属

**期望的结果**
期望的结果是什么（A clear and concise description of what you expected to happen.）
希望是直接去的枚举的name
比如：ENTITY

是否现在支持？多谢解答

**Comment by liaochong** [comment]
抱歉，现在不支持枚举，原因在于枚举是多样性的，每一次导出具体是枚举的名称还是其中的属性，无法作出方便的判断，因此无法通用，建议自行转换成对应的基本数据结构，如string等

**Comment by qinkangdeid** [comment]
> 抱歉，现在不支持枚举，原因在于枚举是多样性的，每一次导出具体是枚举的名称还是其中的属性，无法作出方便的判断，因此无法通用，建议自行转换成对应的基本数据结构，如string等

好的 明白  谢谢大佬
